const state={data:null,index:null,coverage:null,loadedShards:new Set(),pendingShards:new Map(),rankings:new Map(),pendingRankings:new Map(),view:'overview',metric:'gdp_current_usd',rankingYear:null,country:'USA',compare:['USA','CHN','DEU','IND'],compareMode:'absolute',baseYear:2000,startYear:null,endYear:null,search:'',category:'all',source:'all',recency:'all',sort:'year_desc',page:1,pageSize:50,timings:[]};
const colors=['#2463eb','#d59024','#277c6a','#b84a62','#7357b8','#23859a'];
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

async function init(){
  applyUrlState();const started=performance.now();
  try{const response=await fetch('data/catalog.json');if(!response.ok)throw new Error(`Catalog request failed (${response.status})`);state.data={...(await response.json()),observations:[]};recordTiming('catalog_load',started);}
  catch(error){showFatal('Catalog unavailable','The published data catalog could not be loaded.',error);return;}
  try{const response=await fetch('data/coverage.json');if(response.ok)state.coverage=await response.json();}catch(error){console.warn('[atlas:coverage]',error);}
  state.index=buildIndex();state.startYear=state.startYear||state.data.meta.start_year;state.endYear=state.endYear||state.data.meta.end_year;
  if(!state.data.countries.some(row=>row.iso3===state.country))state.country=state.data.countries[0].iso3;
  $('#freshness').textContent=`Snapshot ${shortDate(state.data.meta.generated_at)}`;$('#coverage-pill').textContent=`${state.data.meta.universe_size} economies · ${state.data.meta.reference_year} cohort`;
  $('#country-search-list').innerHTML=state.data.countries.map(c=>`<option value="${escapeHtml(c.name)}">${c.iso3}</option>`).join('');
  $('#nav').addEventListener('click',event=>{if(!event.target.dataset.view)return;state.view=event.target.dataset.view;state.page=1;syncUrl();render();});
  $('#download-button').addEventListener('click',downloadCSV);$('#share-button').addEventListener('click',copyView);
  $('#global-search').addEventListener('change',event=>{const query=event.target.value.toLowerCase();const found=state.data.countries.find(c=>c.name.toLowerCase()===query||c.iso3.toLowerCase()===query)||state.data.countries.find(c=>c.name.toLowerCase().includes(query));if(found){state.country=found.iso3;state.view='country';syncUrl();render();event.target.value='';}});
  window.addEventListener('popstate',()=>{applyUrlState();render();});$('#loading').hidden=true;$('#app').hidden=false;await render();
}

function buildIndex(){const metrics=new Map(),countries=new Map(),byMetric=new Map(),series=new Map(),latest=new Map(),metricMax=new Map();state.data.metrics.forEach(m=>metrics.set(m.metric_id,m));state.data.countries.forEach(c=>countries.set(c.iso3,c));for(const o of state.data.observations){if(!byMetric.has(o.metric_id))byMetric.set(o.metric_id,[]);byMetric.get(o.metric_id).push(o);const key=`${o.metric_id}|${o.iso3}`;if(!series.has(key))series.set(key,[]);series.get(key).push(o);if(o.value!=null){const current=latest.get(key);if(!current||o.year>current.year)latest.set(key,o);metricMax.set(o.metric_id,Math.max(metricMax.get(o.metric_id)||0,o.year));}}series.forEach(rows=>rows.sort((a,b)=>a.year-b.year));return{metrics,countries,byMetric,series,latest,metricMax};}
function metric(id){return state.index.metrics.get(id)}function countryMeta(iso){return state.index.countries.get(iso)}function latest(id,iso){return state.index.latest.get(`${id}|${iso}`)||null}function series(id,iso){return state.index.series.get(`${id}|${iso}`)||[]}function at(id,iso,year){return series(id,iso).find(row=>row.year===year&&row.value!=null)||null}

async function loadMetric(id){if(state.loadedShards.has(id))return;if(state.pendingShards.has(id))return state.pendingShards.get(id);const url=state.data.observation_shards[id];const promise=(async()=>{const started=performance.now(),response=await fetch(url);if(!response.ok)throw new Error(`Metric shard failed (${response.status})`);const rows=await response.json();state.data.observations.push(...rows);state.loadedShards.add(id);state.index=buildIndex();recordTiming('metric_shard_load',started,{metric_id:id,rows:rows.length});state.pendingShards.delete(id);})();state.pendingShards.set(id,promise);return promise;}
async function loadRanking(id){if(state.rankings.has(id))return state.rankings.get(id);if(state.pendingRankings.has(id))return state.pendingRankings.get(id);const promise=(async()=>{const response=await fetch(state.data.ranking_shards[id]);if(!response.ok)throw new Error(`Ranking shard failed (${response.status})`);const asset=await response.json();state.rankings.set(id,asset);state.pendingRankings.delete(id);return asset;})();state.pendingRankings.set(id,promise);return promise;}
function requiredMetrics(){if(['country','coverage'].includes(state.view))return state.data.metrics.map(m=>m.metric_id);if(state.view==='overview')return state.data.overview_metric_ids;if(['rankings','compare','data'].includes(state.view))return[state.metric];return[];}
function requiredRankings(){if(state.view==='overview')return state.data.overview_metric_ids;if(state.view==='country')return state.data.metrics.map(m=>m.metric_id);if(state.view==='rankings')return[state.metric];return[];}
async function render(){try{await Promise.all(requiredMetrics().map(loadMetric));await Promise.all(requiredRankings().map(loadRanking));}catch(error){$('#app').innerHTML=errorState('Analytical asset unavailable',error.message);return;}
  $$('#nav button').forEach(button=>{const active=button.dataset.view===state.view;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false')});
  const titles={overview:'World overview',rankings:'Economic rankings',compare:'Compare economies',country:'Country intelligence',coverage:'Data coverage',data:'Data explorer',methodology:'Methodology & sources',diagnostics:'Build diagnostics'};$('#page-title').textContent=titles[state.view];
  const views={overview,rankings,compare,country,coverage:coverageView,data:explorer,methodology,diagnostics};$('#app').innerHTML=views[state.view]();bind();drawCharts();
}

function ranking(id,year=null){const asset=state.rankings.get(id);if(!asset)return null;const selected=year||state.rankingYear||asset.default_ranking_year;return asset.rankings[String(selected)]||asset.rankings[String(asset.default_ranking_year)];}
function recency(latestYear,maxYear){if(latestYear==null)return{lag:null,status:'unavailable'};const lag=maxYear-latestYear;return{lag,status:lag===0?'current_year':lag===1?'prior_year':'historical'};}
function statusLabel(status){return({current_year:'Current year',prior_year:'Prior year',historical:'Historical',unavailable:'Unavailable'})[status]||status;}
function fmt(value,type='number',decimals){if(value==null||!Number.isFinite(Number(value)))return'—';const n=Number(value),d=decimals??(type==='percent'?1:2);if(type==='currency')return`$${abbreviate(n,d)}`;if(type==='percent')return`${n.toFixed(d)}%`;if(type==='integer')return Math.round(n).toLocaleString();return abbreviate(n,d);}
function abbreviate(n,d=2){const a=Math.abs(n);if(a>=1e12)return`${(n/1e12).toFixed(d)}T`;if(a>=1e9)return`${(n/1e9).toFixed(d)}B`;if(a>=1e6)return`${(n/1e6).toFixed(d)}M`;if(a>=1e3)return`${(n/1e3).toFixed(d)}K`;return n.toLocaleString(undefined,{maximumFractionDigits:d});}
function shortDate(value){return new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}function years(){return Array.from({length:state.data.meta.end_year-state.data.meta.start_year+1},(_,i)=>state.data.meta.start_year+i);}
function provenance(m,observation=null){return`<details class="provenance"><summary>Source & definition</summary><dl><dt>Organization</dt><dd>World Bank</dd><dt>Dataset</dt><dd>World Development Indicators</dd><dt>Indicator</dt><dd><code>${escapeHtml(m.code)}</code></dd><dt>Definition</dt><dd>${escapeHtml(m.description)}</dd><dt>Observation year</dt><dd>${observation?.year??'Varies'}</dd><dt>Retrieved</dt><dd>${observation?shortDate(observation.retrieved_at):shortDate(state.data.meta.generated_at)}</dd><dt>Release</dt><dd><code>${escapeHtml(state.data.meta.release_id)}</code></dd></dl></details>`;}
function kpi(label,value,meta,accent='#2463eb',detail=''){return`<article class="card kpi" style="--accent:${accent}"><div class="kpi-label">${escapeHtml(label)}</div><div class="kpi-value">${escapeHtml(value)}</div><div class="kpi-meta">${meta}</div>${detail}</article>`;}
function badge(status,lag){return`<span class="status status-${status}">${statusLabel(status)}${lag==null?'':` · ${lag}y lag`}</span>`;}
function metricSelect(){return`<div class="field"><label for="metric-select">Metric</label><select id="metric-select">${state.data.metrics.map(m=>`<option value="${m.metric_id}" ${m.metric_id===state.metric?'selected':''}>${escapeHtml(m.name)}</option>`).join('')}</select></div>`;}
function countryOptions(selected){return state.data.countries.map(c=>`<option value="${c.iso3}" ${selected.includes(c.iso3)?'selected':''}>${String(c.gdp_rank).padStart(2,'0')} · ${escapeHtml(c.name)}</option>`).join('');}
function rankingYearSelect(asset){const preferred=[2025,2024,2023,2020,2015,2010,2005,2000],available=asset.available_ranking_years,options=[...new Set([...preferred.filter(y=>available.includes(y)),...available])];const selected=state.rankingYear&&available.includes(state.rankingYear)?state.rankingYear:asset.default_ranking_year;return`<div class="field"><label for="ranking-year">Ranking year</label><select id="ranking-year">${options.map(y=>`<option ${y===selected?'selected':''}>${y}</option>`).join('')}</select></div>`;}

function overview(){const modules=[['gdp_current_usd','Global economy','Largest economies by nominal GDP'],['gdp_growth_pct','Fastest real growth','Common-year annual growth'],['inflation_cpi_pct','Highest inflation','Common-year CPI change'],['unemployment_pct','Lowest unemployment','Ascending common-year comparison'],['central_government_debt_pct_gdp','Central-government debt','Limited common-year coverage']];return`<div class="brief"><div><span class="eyebrow">RELEASE ${escapeHtml(state.data.meta.release_id)}</span><h2>One cohort. Comparable years. Traceable evidence.</h2><p>Every overview module uses one explicit observation year and keeps missing economies visible. Coverage is part of the result, not a footnote.</p></div><span class="source-chip"><i></i>WORLD BANK WDI</span></div><section class="overview-grid">${modules.map(([id,title,subtitle])=>overviewModule(id,title,subtitle)).join('')}</section>`;}
function overviewModule(id,title,subtitle){const asset=state.rankings.get(id),r=ranking(id,asset.default_ranking_year),m=metric(id);let rows=r.rows.filter(x=>x.rank);if(id==='unemployment_pct')rows=rows.slice().sort((a,b)=>a.value-b.value||a.iso3.localeCompare(b.iso3));rows=rows.slice(0,6);return`<article class="panel overview-module"><div class="panel-head"><div><h3>${title}</h3><div class="panel-sub">${subtitle} · ${m.unit}</div></div><span class="coverage-chip">${r.ranked_entity_count}/${r.cohort_size} · ${r.ranking_year}</span></div><div class="rank-list">${rows.map((row,i)=>rankRow(id==='unemployment_pct'?i+1:row.rank,row.country,row.iso3,fmt(row.value,m.format,m.preferred_decimals))).join('')}</div>${id==='central_government_debt_pct_gdp'?`<div class="note">${r.ranked_entity_count}/50 observed in 2024 · 35/50 have any historical observation.</div>`:''}<button class="text-button" data-open-ranking="${id}" data-ranking-year="${r.ranking_year}">Open full ranking →</button></article>`;}

function rankings(){const asset=state.rankings.get(state.metric),r=ranking(state.metric),m=metric(state.metric);state.rankingYear=r.ranking_year;return`<div class="brief"><div><span class="eyebrow">RANK WITHIN THE ATLAS ANALYTICAL COHORT</span><h2>${escapeHtml(m.name)} ranking</h2><p>Only observations from ${r.ranking_year} receive a rank. Older values appear separately as historical context and never enter the ranking.</p></div><div class="ranking-summary"><strong>Ranking year: ${r.ranking_year}</strong><span>Coverage: ${r.ranked_entity_count} / ${r.cohort_size} economies</span></div></div><div class="controls">${metricSelect()}${rankingYearSelect(asset)}<div class="field"><label for="search">Search economy</label><input id="search" value="${escapeHtml(state.search)}" placeholder="United, Korea, Brazil"></div></div>${rankingTable(r,m)}<section class="panel rank-history-panel"><div class="panel-head"><div><h3>Country rank history</h3><div class="panel-sub">Rank within the Atlas analytical cohort · exact-year observations only</div></div><select id="rank-country">${countryOptions([state.country])}</select></div><div class="chart" data-chart="rank-history" data-metric="${state.metric}" data-country="${state.country}"></div></section>`;}
function rankingTable(r,m){const query=state.search.toLowerCase(),rows=r.rows.filter(row=>!query||`${row.country} ${row.iso3}`.toLowerCase().includes(query));return`<div class="table-wrap"><table><caption class="sr-only">${escapeHtml(m.name)} ranking for ${r.ranking_year}</caption><thead><tr><th>Rank</th><th>Economy</th><th class="num">Value</th><th>Observation year</th><th>${changeLabel(m,1)}</th><th>Latest historical context</th><th>Recency</th><th>Source</th></tr></thead><tbody>${rows.map(row=>{const change=row.changes?.['1'];return`<tr class="${row.rank?'':'row-missing'}"><td class="num">${row.rank??'—'}</td><th class="country-cell">${escapeHtml(row.country)}<small>${row.iso3}</small></th><td class="num">${row.value==null?`Not available for ${r.ranking_year}`:fmt(row.value,m.format,m.preferred_decimals)}</td><td>${row.observation_year??'—'}</td><td class="num">${formatChange(change,m)}</td><td>${row.value==null&&row.latest_historical_year?`${fmt(row.latest_historical_value,m.format,m.preferred_decimals)} · ${row.latest_historical_year}`:'—'}</td><td>${badge(row.recency_status,row.lag_years)}</td><td><span class="micro">WDI / ${escapeHtml(m.code)}</span></td></tr>`}).join('')}</tbody></table></div>${provenance(m)}`;}
function changeLabel(m,window){return m.change_transformation==='percentage_point_change'?`${window}-year pp change`:`${window}-year CAGR`;}
function formatChange(value,m){if(value==null)return'—';const suffix=m.change_transformation==='percentage_point_change'?' pp':'%';return`${value>0?'+':''}${value.toFixed(1)}${suffix}`;}

function compare(){const selected=state.compare.filter(countryMeta),m=metric(state.metric),canIndex=m.indexing_allowed,stateMode=canIndex?state.compareMode:'absolute';return`<div class="brief"><div><span class="eyebrow">TRAJECTORY COMPARISON</span><h2>Compare economies on one analytical scale.</h2><p>Absolute values preserve the metric’s native unit. Indexed trajectories set each selected economy’s observed base-year value to 100; they do not change the underlying metric definition.</p></div></div><div class="controls"><div class="field"><label for="compare-countries">Economies</label><select id="compare-countries" multiple size="5">${countryOptions(selected)}</select></div>${metricSelect()}${canIndex?`<div class="field"><label for="compare-mode">Display</label><select id="compare-mode"><option value="absolute" ${stateMode==='absolute'?'selected':''}>Absolute values</option><option value="indexed" ${stateMode==='indexed'?'selected':''}>Indexed trajectory</option></select></div><div class="field"><label for="base-year">Index start year</label><select id="base-year">${years().map(y=>`<option ${y===state.baseYear?'selected':''}>${y}</option>`).join('')}</select></div>`:''}${timeRangeControls()}</div>${!canIndex?'<div class="note">Indexing is not enabled for this rate/share metric. Use absolute values in the declared unit.</div>':''}<section class="panel"><div class="panel-head"><div><h3>${escapeHtml(m.name)} trajectories</h3><div class="panel-sub">${stateMode==='indexed'?`Selected start year ${state.baseYear} = 100`:`${m.unit} · ${state.startYear}-${state.endYear}`}</div></div><div class="legend">${selected.map((iso,i)=>`<span><i style="background:${colors[i]}"></i>${escapeHtml(countryMeta(iso).name)}</span>`).join('')}</div></div><div class="chart" data-chart="lines" data-metric="${state.metric}" data-countries="${selected}" data-rebase="${stateMode==='indexed'?state.baseYear:''}"></div>${provenance(m)}</section>`;}
function timeRangeControls(){return`<div class="field"><label for="start-year">Start</label><select id="start-year">${years().map(y=>`<option ${y===state.startYear?'selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="end-year">End</label><select id="end-year">${years().map(y=>`<option ${y===state.endYear?'selected':''}>${y}</option>`).join('')}</select></div>`;}

function country(){const c=countryMeta(state.country),ids=state.data.metrics.map(m=>m.metric_id);return`<div class="controls"><div class="field"><label for="country-select">Economy</label><select id="country-select">${countryOptions([state.country])}</select></div></div><section class="country-hero"><div><span class="eyebrow">${escapeHtml(c.region)} · ${escapeHtml(c.income_group)}</span><h2>${escapeHtml(c.name)}</h2><p>${c.iso3} · approved Atlas cohort · eligibility ${c.analytical_eligibility}</p></div><div class="hero-rank"><span class="micro">NOMINAL GDP RANK · ${c.reference_year}</span><strong>#${String(c.gdp_rank).padStart(2,'0')}</strong></div></section><h3 class="section-title">Snapshot</h3><section class="kpis kpis-wide">${ids.map((id,i)=>countryMetricCard(id,c.iso3,colors[i%colors.length])).join('')}</section><h3 class="section-title">Historical performance</h3><section class="history-grid">${ids.filter(id=>id!=='population').map(id=>{const m=metric(id);return`<article class="panel compact-chart"><div class="panel-head"><div><h3>${escapeHtml(m.name)}</h3><div class="panel-sub">${m.unit} · observed values only</div></div></div><div class="chart" data-chart="lines" data-metric="${id}" data-countries="${c.iso3}"></div></article>`}).join('')}</section><h3 class="section-title">Relative position</h3>${relativeTable(c.iso3)}<h3 class="section-title">Data coverage</h3>${countryCoverage(c.iso3)}`;}
function countryMetricCard(id,iso,accent){const m=metric(id),o=latest(id,iso),max=state.index.metricMax.get(id),fresh=recency(o?.year,max),r=ranking(id,max),row=r?.rows.find(x=>x.iso3===iso);return kpi(m.name,o?fmt(o.value,m.format,m.preferred_decimals):'Not available',`${o?`Observed ${o.year}`:'No observation'} · ${badge(fresh.status,fresh.lag)}${row?.rank?`<br>Rank ${row.rank}/${r.ranked_entity_count} in ${r.ranking_year}`:''}`,accent,provenance(m,o));}
function relativeTable(iso){return`<div class="table-wrap"><table><thead><tr><th>Metric</th><th>Ranking year</th><th>Rank</th><th>Coverage</th><th class="num">Country value</th><th class="num">Cohort median</th><th>${changeLabel({change_transformation:'cagr'},5)} / pp</th><th>10-year change</th></tr></thead><tbody>${state.data.metrics.map(m=>{const asset=state.rankings.get(m.metric_id),r=ranking(m.metric_id,asset.default_ranking_year),row=r.rows.find(x=>x.iso3===iso),values=r.rows.filter(x=>x.value!=null).map(x=>x.value).sort((a,b)=>a-b),med=values.length?values[Math.floor(values.length/2)]:null;return`<tr><th>${escapeHtml(m.name)}</th><td>${r.ranking_year}</td><td>${row.rank??'—'}</td><td>${r.ranked_entity_count}/${r.cohort_size}</td><td class="num">${fmt(row.value,m.format,m.preferred_decimals)}</td><td class="num">${fmt(med,m.format,m.preferred_decimals)}</td><td class="num">${formatChange(row.changes?.['5'],m)}</td><td class="num">${formatChange(row.changes?.['10'],m)}</td></tr>`}).join('')}</tbody></table></div>`;}
function countryCoverage(iso){const rows=state.coverage?.country_metric?.filter(row=>row.iso3===iso)||[];return`<div class="coverage coverage-detailed">${state.data.metrics.map(m=>{const row=rows.find(x=>x.metric_id===m.metric_id)||{observation_count:0,earliest_year:null,latest_year:null,recency_status:'unavailable',lag_years:null};return`<article class="coverage-cell"><b>${escapeHtml(m.name)}</b><span>${row.observation_count} observations</span><span>${row.earliest_year??'—'}–${row.latest_year??'—'}</span>${badge(row.recency_status,row.lag_years)}</article>`}).join('')}</div>`;}

function coverageView(){const rows=state.coverage?.country_metric||[];return`<div class="brief"><div><span class="eyebrow">DATA AVAILABILITY</span><h2>Coverage is part of the evidence.</h2><p>Inspect country × metric availability, observation spans, and structural recency relative to each metric’s maximum year.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label for="recency-filter">Recency</label><select id="recency-filter"><option value="all">All statuses</option>${['current_year','prior_year','historical','unavailable'].map(x=>`<option value="${x}" ${state.recency===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></div><div class="field"><label for="search">Search economy</label><input id="search" value="${escapeHtml(state.search)}"></div></div><div class="coverage-summary">${state.coverage.inventory.map(row=>kpi(row.display_name,`${row.ranking_year_observed_country_count}/50`,`Observed in ${row.ranking_year} · ${row.ever_observed_country_count}/50 ever observed`)).join('')}</div>${coverageTable(rows)}`;}
function coverageTable(rows){const query=state.search.toLowerCase();const filtered=rows.filter(row=>row.metric_id===state.metric&&(!query||`${row.country} ${row.iso3}`.toLowerCase().includes(query))&&(state.recency==='all'||row.recency_status===state.recency));return`<div class="table-wrap"><table><thead><tr><th>Economy</th><th>Metric</th><th>Earliest</th><th>Latest</th><th>Observations</th><th>Metric maximum</th><th>Lag</th><th>Status</th></tr></thead><tbody>${filtered.map(row=>`<tr><th class="country-cell">${escapeHtml(row.country)}<small>${row.iso3}</small></th><td>${escapeHtml(metric(row.metric_id).name)}</td><td>${row.earliest_year??'—'}</td><td>${row.latest_year??'—'}</td><td>${row.observation_count}</td><td>${row.metric_max_year??'—'}</td><td>${row.lag_years??'—'}</td><td>${badge(row.recency_status,row.lag_years)}</td></tr>`).join('')}</tbody></table></div>`;}

function explorer(){const all=filteredExplorerRows(),pages=Math.max(1,Math.ceil(all.length/state.pageSize));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*state.pageSize,state.page*state.pageSize);return`<div class="brief"><div><span class="eyebrow">CANONICAL OBSERVATIONS</span><h2>Filter, inspect, and export the evidence layer.</h2><p>Filtered exports preserve source, observation period, retrieval timestamp, raw snapshot, and pipeline lineage.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label for="category-filter">Category</label><select id="category-filter"><option value="all">All categories</option>${[...new Set(state.data.metrics.map(m=>m.category))].map(x=>`<option ${state.category===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select></div><div class="field"><label for="source-filter">Source</label><select id="source-filter"><option value="all">All sources</option>${state.data.sources.map(x=>`<option value="${x.source_id}" ${state.source===x.source_id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><div class="field"><label for="recency-filter">Recency</label><select id="recency-filter"><option value="all">All statuses</option>${['current_year','prior_year','historical'].map(x=>`<option value="${x}" ${state.recency===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></div><div class="field"><label for="search">Country</label><input id="search" value="${escapeHtml(state.search)}" placeholder="Country or ISO3"></div>${timeRangeControls()}<div class="field"><label for="sort-select">Sort</label><select id="sort-select"><option value="year_desc" ${state.sort==='year_desc'?'selected':''}>Newest first</option><option value="country" ${state.sort==='country'?'selected':''}>Country</option><option value="value_desc" ${state.sort==='value_desc'?'selected':''}>Value high–low</option></select></div></div><div class="table-wrap"><table><thead><tr><th>Economy</th><th>Year</th><th>Metric</th><th class="num">Value</th><th>Recency</th><th>Indicator</th><th>Retrieved</th></tr></thead><tbody>${rows.map(o=>{const m=metric(o.metric_id),fresh=recency(o.year,state.index.metricMax.get(o.metric_id));return`<tr><th class="country-cell">${escapeHtml(countryMeta(o.iso3).name)}<small>${o.iso3}</small></th><td>${o.year}</td><td>${escapeHtml(m.name)}</td><td class="num">${fmt(o.value,m.format,m.preferred_decimals)}</td><td>${badge(fresh.status,fresh.lag)}</td><td><code>${escapeHtml(o.source_indicator_id)}</code></td><td>${shortDate(o.retrieved_at)}</td></tr>`}).join('')}</tbody></table></div><div class="pagination"><button data-page="${state.page-1}" ${state.page===1?'disabled':''}>Previous</button><span>Page ${state.page} of ${pages} · ${all.length.toLocaleString()} observations</span><button data-page="${state.page+1}" ${state.page===pages?'disabled':''}>Next</button></div>`;}
function filteredExplorerRows(){const query=state.search.toLowerCase();let rows=(state.index.byMetric.get(state.metric)||[]).filter(o=>o.year>=state.startYear&&o.year<=state.endYear&&(!query||`${countryMeta(o.iso3).name} ${o.iso3}`.toLowerCase().includes(query))&&(state.category==='all'||metric(o.metric_id).category===state.category)&&(state.source==='all'||o.source_id===state.source));if(state.recency!=='all')rows=rows.filter(o=>recency(o.year,state.index.metricMax.get(o.metric_id)).status===state.recency);return rows.slice().sort(state.sort==='country'?(a,b)=>a.iso3.localeCompare(b.iso3)||b.year-a.year:state.sort==='value_desc'?(a,b)=>b.value-a.value:bYear);}
function bYear(a,b){return b.year-a.year||a.iso3.localeCompare(b.iso3)}

function methodology(){return`<div class="method"><section><span class="eyebrow">ANALYTICAL COHORT</span><h3>Explicit eligibility, source-neutral universe architecture</h3><p>GDP ranking uses a common ${state.data.meta.reference_year} World Bank observation year for source-covered candidates. The candidate universe follows eligibility policy <code>${escapeHtml(state.data.meta.eligibility_policy_version)}</code> and may exclude entities unavailable from the GDP source. The current provider is <code>${escapeHtml(state.data.meta.universe_provider_id)}</code>; an approved provider/registry change can supply a normalized IMF WEO GDP series without rewriting selection logic.</p></section><section><span class="eyebrow">SAME-YEAR RANKING</span><h3>No historical fallback enters a rank</h3><p>Each ranking declares one year. Only observations in that exact year receive sequential ranks; ties resolve by ISO3. Missing economies remain visible and may show a separately labelled latest historical value.</p></section><section><span class="eyebrow">OBSERVATION RECENCY</span><h3>Structural status, not a quality score</h3><p>Annual recency is measured against each metric’s maximum year: current year (lag 0), prior year (lag 1), historical (lag 2+), or unavailable. Retrieval date never substitutes for observation year.</p></section><section><span class="eyebrow">MISSING DATA</span><h3>Published observations only</h3><p>No interpolation, carry-forward, or modeled ranking fallback is used. Current-dollar metrics remain current-dollar metrics; indexing changes the visual comparison scale, not the economic definition.</p></section><section><span class="eyebrow">SOURCE REGISTRY</span><h3>World Bank — World Development Indicators</h3><p>Primary multilateral source · CC BY 4.0 · retrieved ${shortDate(state.data.meta.generated_at)}. <a href="${state.data.sources[0].url}" target="_blank" rel="noreferrer">Open source documentation ↗</a></p></section>${state.data.metrics.map(m=>`<section><span class="eyebrow">${m.code} · ${m.family.toUpperCase()}</span><h3>${escapeHtml(m.name)}</h3><p>${escapeHtml(m.description)}</p><p><b>Unit:</b> ${escapeHtml(m.unit)}. <b>Frequency:</b> ${m.frequency}. <b>Change method:</b> ${escapeHtml(m.change_transformation)}. <b>Caveat:</b> ${escapeHtml(m.caveats)}</p></section>`).join('')}</div>`;}
function diagnostics(){const meta=state.data.meta;return`<div class="brief"><div><h2>Build diagnostics</h2><p>Operational metadata only; no economic quality judgment.</p></div></div><section class="kpis">${kpi('Data release',meta.release_id,`Pipeline ${meta.pipeline_run_id}`)}${kpi('Eligibility policy',meta.eligibility_policy_version,`${meta.universe_provider_id} provider`)}${kpi('Loaded metrics',`${state.loadedShards.size}/${state.data.metrics.length}`,`${state.data.observations.length.toLocaleString()} observations`)}${kpi('Candidate completeness',meta.candidate_universe_complete?'Complete':'Limited','Taiwan/source-unavailable disclosure')}</section>`;}

function rankRow(rank,name,sub,value){return`<div class="rank-row"><span class="rank-num">${rank}</span><span class="rank-name">${escapeHtml(name)}<small>${escapeHtml(sub)}</small></span><span class="rank-value">${escapeHtml(value)}</span></div>`;}
function errorState(title,message){return`<section class="panel empty-state" role="alert"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p></section>`}function showFatal(title,message,error){$('#loading').innerHTML=errorState(title,message);console.error('[atlas:fatal]',error)}function recordTiming(name,started,detail={}){state.timings.push({name,duration_ms:+(performance.now()-started).toFixed(1),...detail});}

function bind(){
  $('#metric-select')?.addEventListener('change',e=>{state.metric=e.target.value;state.rankingYear=null;state.page=1;syncUrl();render()});
  $('#ranking-year')?.addEventListener('change',e=>{state.rankingYear=+e.target.value;syncUrl();render()});
  $('#country-select')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render()});$('#rank-country')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render()});
  $('#compare-countries')?.addEventListener('change',e=>{state.compare=[...e.target.selectedOptions].map(o=>o.value).slice(0,6);syncUrl();render()});$('#compare-mode')?.addEventListener('change',e=>{state.compareMode=e.target.value;syncUrl();render()});$('#base-year')?.addEventListener('change',e=>{state.baseYear=+e.target.value;syncUrl();render()});
  $('#start-year')?.addEventListener('change',e=>{state.startYear=Math.min(+e.target.value,state.endYear);state.page=1;syncUrl();render()});$('#end-year')?.addEventListener('change',e=>{state.endYear=Math.max(+e.target.value,state.startYear);state.page=1;syncUrl();render()});
  $('#search')?.addEventListener('input',e=>{state.search=e.target.value;state.page=1;render()});$('#category-filter')?.addEventListener('change',e=>{state.category=e.target.value;state.page=1;syncUrl();render()});$('#source-filter')?.addEventListener('change',e=>{state.source=e.target.value;state.page=1;syncUrl();render()});$('#recency-filter')?.addEventListener('change',e=>{state.recency=e.target.value;state.page=1;syncUrl();render()});$('#sort-select')?.addEventListener('change',e=>{state.sort=e.target.value;syncUrl();render()});
  $$('[data-page]').forEach(button=>button.addEventListener('click',()=>{state.page=+button.dataset.page;render()}));$$('[data-open-ranking]').forEach(button=>button.addEventListener('click',()=>{state.metric=button.dataset.openRanking;state.rankingYear=+button.dataset.rankingYear;state.view='rankings';syncUrl();render()}));
}
function drawCharts(){$$('[data-chart="lines"]').forEach(drawLineChart);$$('[data-chart="rank-history"]').forEach(drawRankHistory);}
function drawLineChart(el){const started=performance.now(),ids=el.dataset.countries.split(',').filter(Boolean),metricId=el.dataset.metric,base=+(el.dataset.rebase||0),m=metric(metricId);const sets=ids.map(iso=>{let rows=series(metricId,iso).filter(o=>o.value!=null&&o.year>=state.startYear&&o.year<=state.endYear);if(base){const baseValue=at(metricId,iso,base)?.value;rows=rows.map(row=>({...row,value:baseValue?row.value/baseValue*100:null})).filter(row=>row.value!=null);}return{iso,rows}}).filter(set=>set.rows.length);renderLine(el,sets,base?'Index, selected start year = 100':m.unit,started,metricId);}
function drawRankHistory(el){const asset=state.rankings.get(el.dataset.metric),iso=el.dataset.country,rows=asset.available_ranking_years.slice().sort((a,b)=>a-b).map(year=>{const row=asset.rankings[String(year)].rows.find(x=>x.iso3===iso);return row?.rank?{year,value:row.rank}:null}).filter(Boolean);renderLine(el,[{iso,rows}],`Rank within Atlas cohort · 1 is highest`,performance.now(),el.dataset.metric,true);}
function renderLine(el,sets,label,started,metricId,invert=false){if(!sets.length){el.innerHTML='<div class="empty">No observed values for this selection.</div>';return}const all=sets.flatMap(s=>s.rows),xs=all.map(r=>r.year),ys=all.map(r=>r.value),minX=Math.min(...xs),maxX=Math.max(...xs),minY=invert?1:Math.min(...ys),maxY=Math.max(...ys),W=820,H=300,p={l:58,r:18,t:24,b:36},x=v=>p.l+(v-minX)/(maxX-minX||1)*(W-p.l-p.r),y=v=>p.t+(invert?(v-minY):(maxY-v))/(maxY-minY||1)*(H-p.t-p.b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${escapeHtml(metric(metricId).name)} chart"><text x="8" y="13" class="axis-label">${escapeHtml(label.toUpperCase())}</text>`;for(let i=0;i<5;i++){const val=minY+(maxY-minY)*i/4,py=y(val);svg+=`<line x1="${p.l}" y1="${py}" x2="${W-p.r}" y2="${py}" class="grid-line"/><text x="${p.l-8}" y="${py+3}" text-anchor="end" class="axis-label">${invert?Math.round(val):compact(val)}</text>`}for(let yr=Math.ceil(minX/5)*5;yr<=maxX;yr+=5)svg+=`<text x="${x(yr)}" y="${H-10}" text-anchor="middle" class="axis-label">${yr}</text>`;sets.forEach((set,i)=>{const d=set.rows.map((r,j)=>`${j?'L':'M'}${x(r.year)},${y(r.value)}`).join(' ');svg+=`<path d="${d}" class="line" stroke="${colors[i]}"/>${set.rows.map(r=>`<circle cx="${x(r.year)}" cy="${y(r.value)}" r="3" fill="${colors[i]}" class="dot"><title>${escapeHtml(countryMeta(set.iso).name)} · ${r.year} · ${invert?`Rank ${r.value}`:fmt(r.value,metric(metricId).format)}</title></circle>`).join('')}`});el.innerHTML=svg+'</svg>';recordTiming('chart_render',started,{metric_id:metricId,points:all.length});}
function compact(v){const a=Math.abs(v);return a>=1e12?`${(v/1e12).toFixed(1)}T`:a>=1e9?`${(v/1e9).toFixed(0)}B`:a>=1e6?`${(v/1e6).toFixed(0)}M`:v.toFixed(a<10?1:0);}

function applyUrlState(){const params=new URLSearchParams(location.search),views=['overview','rankings','compare','country','coverage','data','methodology','diagnostics'];if(views.includes(params.get('view')))state.view=params.get('view');if(/^[a-z0-9_]+$/.test(params.get('metric')||''))state.metric=params.get('metric');if(/^[A-Z]{3}$/.test(params.get('country')||''))state.country=params.get('country');const compare=(params.get('countries')||'').split(',').filter(x=>/^[A-Z]{3}$/.test(x)).slice(0,6);if(compare.length)state.compare=compare;for(const[key,target]of[['year','rankingYear'],['base','baseYear'],['start','startYear'],['end','endYear']]){const value=+params.get(key);if(Number.isInteger(value)&&value>=1900&&value<=2200)state[target]=value}if(['absolute','indexed'].includes(params.get('mode')))state.compareMode=params.get('mode');state.search=params.get('q')||'';state.category=params.get('category')||'all';state.source=params.get('source')||'all';state.recency=params.get('recency')||'all';state.sort=params.get('sort')||'year_desc';}
function syncUrl(){const params=new URLSearchParams({view:state.view,metric:state.metric});if(state.rankingYear)params.set('year',state.rankingYear);if(state.view==='country'||state.view==='rankings')params.set('country',state.country);if(state.view==='compare'){params.set('countries',state.compare.join(','));params.set('mode',state.compareMode);params.set('base',state.baseYear)}if(state.startYear)params.set('start',state.startYear);if(state.endYear)params.set('end',state.endYear);if(state.search)params.set('q',state.search);if(state.category!=='all')params.set('category',state.category);if(state.source!=='all')params.set('source',state.source);if(state.recency!=='all')params.set('recency',state.recency);if(state.sort!=='year_desc')params.set('sort',state.sort);history.pushState(null,'',`${location.pathname}?${params}`);}
async function copyView(){await navigator.clipboard.writeText(location.href);const button=$('#share-button');button.textContent='Copied';setTimeout(()=>button.textContent='Copy view',1500);}
function downloadCSV(){const rows=filteredExplorerRows(),head=['country','iso3','year','metric_id','metric_name','value','unit','recency_status','lag_years','source_id','source_dataset_id','source_indicator_id','retrieved_at','raw_snapshot_id','raw_record_index','pipeline_run_id','release_id'],csv=[head.join(','),...rows.map(o=>{const m=metric(o.metric_id),fresh=recency(o.year,state.index.metricMax.get(o.metric_id));return[countryMeta(o.iso3).name,o.iso3,o.year,o.metric_id,m.name,o.value,o.unit,fresh.status,fresh.lag,o.source_id,o.source_dataset_id,o.source_indicator_id,o.retrieved_at,o.raw_snapshot_id,o.raw_record_index,o.pipeline_run_id,state.data.meta.release_id].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')})].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`atlas-${state.metric}-${state.startYear}-${state.endYear}.csv`;link.click();URL.revokeObjectURL(link.href);}

init();
