const state = { data: null, index: null, loadedShards: new Set(), pendingShards: new Map(), shardErrors: new Map(), view: 'overview', metric: 'gdp_current_usd', country: 'USA', compare: ['USA','CHN','DEU','JPN'], baseYear: null, startYear: null, endYear: null, search: '', page: 1, pageSize: 100, timings: [] };
const colors = ['#3374ff','#e6a33a','#5cd6b3','#dc695d','#8c6fd1','#41a4a8','#d876ac','#8091a0'];
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];

async function init(){
  applyUrlState(); const started=performance.now();
  try{const response=await fetch('data/catalog.json');if(!response.ok)throw new Error(`Catalog request failed (${response.status})`);state.data={...(await response.json()),observations:[]};recordTiming('catalog_load',started);}
  catch(err){try{const fallback=await fetch('data/dashboard.json');if(!fallback.ok)throw err;state.data=await fallback.json();state.data.observations=state.data.observations||[];state.data.metrics.forEach(m=>state.loadedShards.add(m.metric_id));}catch(fallbackErr){showFatal('Catalog unavailable','The published data catalog could not be loaded. Verify the static build contains app/data/catalog.json.',fallbackErr);return;}}
  state.index=buildIndex(state.data); $('#loading').hidden=true; $('#app').hidden=false;
  state.baseYear=state.data.meta.reference_year;
  state.startYear=state.startYear||state.data.meta.start_year;state.endYear=state.endYear||state.data.meta.end_year;
  if(!state.data.countries.some(c=>c.iso3===state.country)) state.country=state.data.countries[0].iso3;
  if(!state.data.metrics.some(m=>m.metric_id===state.metric))state.metric='gdp_current_usd';
  $('#freshness').textContent=`Snapshot ${shortDate(state.data.meta.generated_at)}`;
  $('#coverage-pill').textContent=`${state.data.meta.universe_size} economies · ${state.data.meta.reference_year} universe`;
  $('#nav').addEventListener('click', e=>{ if(!e.target.dataset.view)return; state.view=e.target.dataset.view;syncUrl();render(); });
  $('#download-button').addEventListener('click', downloadCSV);
  window.addEventListener('popstate',()=>{applyUrlState();render();});await render();
}
async function render(){
  const required=requiredMetrics();const failed=await loadMetrics(required);if(failed.length){renderShardError(failed);return;}
  $$('#nav button').forEach(b=>{const active=b.dataset.view===state.view;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});
  const titles={overview:'World overview',rankings:'Economic rankings',compare:'Compare economies',country:'Country explorer',data:'Data explorer',methodology:'Methodology & sources',diagnostics:'Build diagnostics'};
  $('#page-title').textContent=titles[state.view];
  $('#app').innerHTML=({overview,rankings,compare,country,data:explorer,methodology,diagnostics})[state.view]();
  bind(); drawCharts();
}
function requiredMetrics(){if(state.view==='overview')return state.data.overview_metric_ids||['gdp_current_usd','gdp_growth_pct','inflation_cpi_pct'];if(state.view==='country')return state.data.metrics.map(m=>m.metric_id);if(['rankings','compare','data'].includes(state.view))return[state.metric];return[];}
async function loadMetrics(ids){const results=await Promise.all(ids.map(loadMetric));return results.filter(Boolean);}
async function loadMetric(id){if(state.loadedShards.has(id))return null;if(state.pendingShards.has(id))return state.pendingShards.get(id);const url=state.data.observation_shards?.[id];if(!url)return `No published shard is registered for ${id}`;const started=performance.now();const promise=(async()=>{try{const response=await fetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const rows=await response.json();if(!Array.isArray(rows))throw new Error('Shard payload is not an array');state.data.observations.push(...rows);state.loadedShards.add(id);state.shardErrors.delete(id);state.index=buildIndex(state.data);recordTiming('metric_shard_load',started,{metric_id:id,rows:rows.length});return null;}catch(error){const message=`${id}: ${error.message}`;state.shardErrors.set(id,message);return message;}finally{state.pendingShards.delete(id);}})();state.pendingShards.set(id,promise);return promise;}
function renderShardError(failures){$('#app').innerHTML=errorState('Metric data unavailable',failures.join(' · '),'<button class="primary" data-retry-shards>Retry</button>');const retry=$('[data-retry-shards]');retry?.addEventListener('click',()=>{state.shardErrors.clear();render();});}
function showFatal(title,message,error){$('#loading').innerHTML=errorState(title,message);console.error('[atlas:data_failure]',error);}
function errorState(title,message,action=''){return `<section class="panel empty-state" role="alert"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p>${action}</div></section>`;}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function recordTiming(name,started,detail={}){const entry={name,duration_ms:+(performance.now()-started).toFixed(1),...detail};state.timings.push(entry);console.debug('[atlas:timing]',entry);}
function buildIndex(data){const metrics=new Map(),countries=new Map(),byMetric=new Map(),series=new Map(),latest=new Map();data.metrics.forEach(m=>metrics.set(m.metric_id,m));data.countries.forEach(c=>countries.set(c.iso3,c));for(const o of data.observations){if(!byMetric.has(o.metric_id))byMetric.set(o.metric_id,[]);byMetric.get(o.metric_id).push(o);const key=`${o.metric_id}|${o.iso3}`;if(!series.has(key))series.set(key,[]);series.get(key).push(o);const current=latest.get(key);if(o.value!=null&&(!current||o.year>current.year))latest.set(key,o);}series.forEach(rows=>rows.sort((a,b)=>a.year-b.year));return{metrics,countries,byMetric,series,latest};}
function latest(metric, iso3){ return iso3?state.index.latest.get(`${metric}|${iso3}`)||null:(state.index.byMetric.get(metric)||[]).filter(o=>o.value!=null).sort((a,b)=>b.year-a.year)[0]||null; }
function at(metric, iso3, year){ return (state.index.series.get(`${metric}|${iso3}`)||[]).find(o=>o.year===year&&o.value!=null); }
function metric(id){ return state.index.metrics.get(id); }
function countryMeta(iso3){ return state.index.countries.get(iso3); }
function fmt(value,type='number',decimals){if(value==null||!Number.isFinite(Number(value)))return '—';const n=Number(value),d=decimals??(type==='percent'?1:2);if(type==='currency')return `$${abbreviate(n,d)}`;if(type==='percent')return `${n.toFixed(d)}%`;if(type==='signed_percent')return `${n>0?'+':''}${n.toFixed(d)}%`;if(type==='basis_points')return `${n.toFixed(d)} bps`;if(type==='integer')return Math.round(n).toLocaleString();if(type==='ratio')return n.toFixed(d);return abbreviate(n,d);}
function abbreviate(n,d=2){const a=Math.abs(n);if(a>=1e12)return `${(n/1e12).toFixed(d)}T`;if(a>=1e9)return `${(n/1e9).toFixed(d)}B`;if(a>=1e6)return `${(n/1e6).toFixed(d)}M`;if(a>=1e3)return `${(n/1e3).toFixed(d)}K`;return n.toLocaleString(undefined,{maximumFractionDigits:d});}
function formatReferencePeriod(value,frequency='annual'){const text=String(value??'');if(frequency==='annual'&&/^\d{4}$/.test(text))return text;if(frequency==='quarterly'&&/^\d{4}-Q[1-4]$/.test(text))return text.replace('-',' ');if(frequency==='monthly'&&/^\d{4}-\d{2}$/.test(text)){const[y,m]=text.split('-');return new Date(Date.UTC(+y,+m-1,1)).toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'});}return text||'—';}
function shortDate(v){return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function observationLabel(id,iso){const o=latest(id,iso);return o?`${fmt(o.value,metric(id).format)} · ${o.year}`:'Not available';}
function kpi(label,value,meta,accent='#3374ff'){return `<article class="card kpi" style="--accent:${accent}"><div class="kpi-label">${escapeHtml(label)}</div><div class="kpi-value">${escapeHtml(value)}</div><div class="kpi-meta">${escapeHtml(meta)}</div></article>`;}
function overview(){
  const total=state.data.countries.reduce((s,c)=>s+c.nominal_gdp,0), leader=state.data.countries[0];
  const fastest=state.data.countries.map(c=>({c,o:latest('gdp_growth_pct',c.iso3)})).filter(x=>x.o).sort((a,b)=>b.o.value-a.o.value)[0];
  const inflation=state.data.countries.map(c=>latest('inflation_cpi_pct',c.iso3)).filter(Boolean);
  const med=inflation.map(o=>o.value).sort((a,b)=>a-b)[Math.floor(inflation.length/2)];
  return `<div class="brief"><div><h2>The world economy, rendered as evidence.</h2><p>A current top-50 universe with comparable histories, explicit observation years, and source-level traceability. Latest available values are never mistaken for a common year.</p></div><span class="source-chip"><i></i>AUTHORITATIVE SOURCE ACTIVE</span></div>
  <section class="kpis">${kpi('Top-50 nominal GDP',fmt(total,'currency'),`Common universe year ${state.data.meta.reference_year}`)}${kpi('Largest economy',leader.name,`${fmt(leader.nominal_gdp,'currency')} · rank 01`,'#5cd6b3')}${kpi('Fastest latest growth',fastest.c.name,`${fmt(fastest.o.value,'percent')} · ${fastest.o.year}`,'#e6a33a')}${kpi('Median latest inflation',fmt(med,'percent'),`${inflation.length} economies with observations`,'#dc695d')}</section>
  <section class="grid-2"><article class="panel"><div class="panel-head"><div><h3>Growth trajectories</h3><div class="panel-sub">Real GDP growth · annual % · five largest economies</div></div><span class="micro">1990–${state.data.meta.end_year}</span></div><div class="chart" data-chart="lines" data-metric="gdp_growth_pct" data-countries="${state.data.countries.slice(0,5).map(c=>c.iso3)}"></div></article><article class="panel"><div class="panel-head"><div><h3>Largest economies</h3><div class="panel-sub">Nominal GDP · current US$ · ${state.data.meta.reference_year}</div></div></div><div class="rank-list">${state.data.countries.slice(0,8).map(c=>rankRow(c.gdp_rank,c.name,c.iso3,fmt(c.nominal_gdp,'currency'))).join('')}</div></article></section>
  <section class="panel"><div class="panel-head"><div><h3>Universe snapshot</h3><div class="panel-sub">Every value shows its own observation year</div></div><button class="primary" data-go="rankings">Explore all rankings</button></div>${rankingTable('gdp_current_usd',10)}</section>`;
}
function rankings(){return `<div class="brief"><div><h2>Rank scale, growth, and resilience.</h2><p>The universe is fixed by nominal GDP in the latest sufficiently complete common year. Metric tables retain that cohort even when observations are unavailable.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label>Search economy</label><input id="search" value="${state.search}" placeholder="Country or ISO3"></div></div><div class="note">Rankings use each economy’s latest available observation for the selected metric. Compare the visible year before interpreting rank.</div>${rankingTable(state.metric,50)}</div>`;}
function rankingTable(metricId,limit){
  const m=metric(metricId); let rows=state.data.countries.map(c=>({c,o:latest(metricId,c.iso3)})).filter(x=>!state.search||`${x.c.name} ${x.c.iso3}`.toLowerCase().includes(state.search.toLowerCase())).sort((a,b)=>(b.o?.value??-Infinity)-(a.o?.value??-Infinity)).slice(0,limit);
  return `<div class="table-wrap"><table><caption class="sr-only">${escapeHtml(m.name)} ranking with observation years, coverage, and source</caption><thead><tr><th scope="col">Rank</th><th scope="col">Economy</th><th scope="col" style="text-align:right">${escapeHtml(m.name)}</th><th scope="col">Observation year</th><th scope="col">Coverage</th><th scope="col">Source</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td class="num">${x.o?String(i+1).padStart(2,'0'):'—'}</td><th scope="row" class="country-cell">${escapeHtml(x.c.name)}<small>${x.c.iso3} · GDP universe rank ${x.c.gdp_rank}</small></th><td class="num ${x.o?'':'missing'}">${x.o?fmt(x.o.value,m.format):'Not available'}</td><td>${x.o?.year??'—'}</td><td>${coverage(metricId,x.c.iso3)}</td><td><span class="micro">WDI / ${escapeHtml(m.code)}</span></td></tr>`).join('')}</tbody></table></div>`;
}
function compare(){
 const selected=state.compare.filter(x=>countryMeta(x)); const base=Math.max(state.data.meta.start_year,state.baseYear||2000);
 return `<div class="brief"><div><h2>One scale. Multiple trajectories.</h2><p>Select up to six economies. Rebase nominal GDP to 100 to compare trajectory rather than size.</p></div></div><div class="controls"><div class="field"><label for="compare-countries">Economies (Cmd/Ctrl to select)</label><select id="compare-countries" multiple size="4">${countryOptions(selected)}</select></div>${metricSelect()}<div class="field"><label for="base-year">Base year</label><select id="base-year">${years().map(y=>`<option ${y===base?'selected':''}>${y}</option>`).join('')}</select></div>${timeRangeControls()}</div><section class="panel"><div class="panel-head"><div><h3>Indexed trajectory</h3><div class="panel-sub">${metric(state.metric).name} · selected base year = 100</div></div><div class="legend">${selected.map((iso,i)=>`<span><i style="background:${colors[i]}"></i>${countryMeta(iso).name}</span>`).join('')}</div></div><div class="chart" data-chart="lines" data-metric="${state.metric}" data-countries="${selected}" data-rebase="${base}"></div></section><section class="kpis" style="margin-top:16px">${selected.map((iso,i)=>kpi(countryMeta(iso).name,observationLabel(state.metric,iso),`GDP universe rank ${countryMeta(iso).gdp_rank}`,colors[i])).join('')}</section>`;
}
function country(){const c=countryMeta(state.country);return `<div class="controls"><div class="field"><label>Economy</label><select id="country-select">${countryOptions([state.country])}</select></div></div><section class="country-hero"><div><span class="eyebrow">${c.region.toUpperCase()} · ${c.income_group.toUpperCase()}</span><h2>${c.name}</h2><p>${c.iso3} · Top-50 universe reference year ${c.reference_year}</p></div><div class="hero-rank"><span class="micro">NOMINAL GDP RANK</span><strong>#${String(c.gdp_rank).padStart(2,'0')}</strong></div></section><section class="kpis">${kpi('Nominal GDP',observationLabel('gdp_current_usd',c.iso3),'Current US$')}${kpi('Real GDP growth',observationLabel('gdp_growth_pct',c.iso3),'Annual change','#5cd6b3')}${kpi('GDP per capita',observationLabel('gdp_per_capita_current_usd',c.iso3),'Current US$ per person','#e6a33a')}${kpi('Population',observationLabel('population',c.iso3),'Midyear estimate','#8c6fd1')}</section><section class="grid-2"><article class="panel"><div class="panel-head"><div><h3>Thirty-year growth story</h3><div class="panel-sub">Real GDP growth · annual %</div></div></div><div class="chart" data-chart="lines" data-metric="gdp_growth_pct" data-countries="${c.iso3}"></div></article><article class="panel"><div class="panel-head"><div><h3>Current economic snapshot</h3><div class="panel-sub">Latest value · observation year</div></div></div><div class="rank-list">${['inflation_cpi_pct','unemployment_pct','central_government_debt_pct_gdp','gdp_per_capita_current_usd'].map(id=>rankRow('',metric(id).name,latest(id,c.iso3)?.year??'No observation',observationLabel(id,c.iso3))).join('')}</div></article></section><section class="panel"><div class="panel-head"><div><h3>Data quality & coverage</h3><div class="panel-sub">Observed years in the requested 1990–${state.data.meta.end_year} window</div></div></div><div class="coverage">${state.data.metrics.map(m=>`<div class="coverage-cell"><b>${coverage(m.metric_id,c.iso3)}</b><span>${m.name}</span></div>`).join('')}</div></section>`;}
function explorer(){const started=performance.now(),m=metric(state.metric),allRows=(state.index.byMetric.get(state.metric)||[]).filter(o=>!state.search||countryMeta(o.iso3).name.toLowerCase().includes(state.search.toLowerCase())).slice().sort((a,b)=>b.year-a.year||a.iso3.localeCompare(b.iso3)),pages=Math.max(1,Math.ceil(allRows.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,rows=allRows.slice(start,start+state.pageSize);queueMicrotask(()=>recordTiming('table_render',started,{metric_id:state.metric,rows:rows.length}));return `<div class="brief"><div><h2>Inspect the underlying observations.</h2><p>Raw and displayed values are kept separately. Phase 1 performs no interpolation; missing observations remain missing.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label for="search">Filter economy</label><input id="search" value="${escapeHtml(state.search)}" placeholder="Country name"></div></div><div class="table-wrap"><table><caption class="sr-only">Filtered observations and provenance</caption><thead><tr><th scope="col">Economy</th><th scope="col">Period</th><th scope="col">Metric</th><th scope="col" style="text-align:right">Raw value</th><th scope="col" style="text-align:right">Displayed value</th><th scope="col">Indicator</th><th scope="col">Retrieved</th></tr></thead><tbody>${rows.map(o=>`<tr><th scope="row" class="country-cell">${escapeHtml(countryMeta(o.iso3).name)}<small>${o.iso3}</small></th><td>${formatReferencePeriod(o.reference_period??o.year,m.frequency)}</td><td>${escapeHtml(m.display_name??m.name)}</td><td class="num">${o.raw_value}</td><td class="num">${fmt(o.value,m.formatting??m.format,m.preferred_decimals)}</td><td class="micro">${escapeHtml(o.source_indicator_id??o.source_indicator)}</td><td>${shortDate(o.retrieved_at)}</td></tr>`).join('')}</tbody></table></div><div class="pagination" aria-label="Data Explorer pages"><button data-page="${state.page-1}" ${state.page===1?'disabled':''}>Previous</button><span>Page ${state.page} of ${pages} · ${allRows.length.toLocaleString()} observations</span><button data-page="${state.page+1}" ${state.page===pages?'disabled':''}>Next</button></div><p class="micro">Export CSV includes the full filtered selection and lineage fields.</p>`;}
function methodology(){return `<div class="method"><section><span class="eyebrow">UNIVERSE CONSTRUCTION</span><h3>How an economy enters the Top 50</h3><p>Atlas ranks sovereign economies by World Bank nominal GDP (<code>NY.GDP.MKTP.CD</code>) in the latest calendar year containing observations for at least 150 non-aggregate economies. The first 50 form the analytical universe. Countries are not silently substituted when another metric is missing.</p></section><section><span class="eyebrow">LAYERED DATA MODEL</span><h3>Fact → transformation → display</h3><p>Raw World Bank API responses are preserved by retrieval date. Staging normalizes country codes and annual dates. The canonical observation layer records <code>iso3</code>, <code>year</code>, <code>metric_id</code>, raw and modeled values, source, indicator, and retrieval timestamp. Phase 1 uses published values without interpolation.</p></section><section><span class="eyebrow">COMPARABILITY GUARDRAILS</span><h3>What these numbers cannot say by themselves</h3><ul><li>Current-dollar GDP is sensitive to exchange rates and is not a living-standard measure.</li><li>GDP growth is real growth; nominal GDP levels must not be used to derive it.</li><li>Latest-available comparisons may combine observation years, which are always displayed.</li><li>Central government debt is not general government debt; institutional scope and coverage differ.</li><li>Modeled ILO unemployment improves coverage but does not eliminate labor-market comparability problems.</li></ul></section><section><span class="eyebrow">SOURCE REGISTRY</span><h3>World Bank — World Development Indicators</h3><p>Primary multilateral source · CC BY 4.0 · retrieved ${shortDate(state.data.meta.generated_at)}. Every observation retains its WDI indicator code. <a href="${state.data.sources[0].url}" target="_blank" rel="noreferrer">Open source documentation ↗</a></p></section>${state.data.metrics.map(m=>`<section><span class="eyebrow">${m.code} · ${m.family.toUpperCase()}</span><h3>${m.name}</h3><p><b>Unit:</b> ${m.unit}. <b>Frequency:</b> ${m.frequency}. <b>Transformation:</b> ${m.transformation}. <b>Caveat:</b> ${m.caveats}</p></section>`).join('')}</div>`;}
function diagnostics(){const meta=state.data.meta;return `<div class="brief"><div><h2>Development diagnostics</h2><p>Operational metadata for the published static build. This view makes no economic quality judgment.</p></div></div><section class="kpis">${kpi('Data release',meta.release_id??'Unversioned',`Pipeline ${meta.pipeline_run_id??'—'}`)}${kpi('Loaded shards',`${state.loadedShards.size}/${state.data.metrics.length}`,`${state.data.observations.length.toLocaleString()} observations`,'#5cd6b3')}${kpi('Sources',String(state.data.sources.length),state.data.sources.map(s=>s.source_id).join(', '),'#e6a33a')}${kpi('Client timings',String(state.timings.length),'Developer-local measurements','#8c6fd1')}</section><section class="panel"><div class="panel-head"><div><h3>Runtime timing log</h3><div class="panel-sub">Durations in milliseconds; no external analytics service</div></div></div><div class="table-wrap"><table><caption class="sr-only">Client-side performance timings</caption><thead><tr><th>Event</th><th class="num">Duration</th><th>Metric</th><th class="num">Rows / points</th></tr></thead><tbody>${state.timings.map(row=>`<tr><td>${escapeHtml(row.name)}</td><td class="num">${row.duration_ms}</td><td>${escapeHtml(row.metric_id??'—')}</td><td class="num">${row.rows??row.points??'—'}</td></tr>`).join('')}</tbody></table></div></section>`;}
function metricSelect(){return `<div class="field"><label for="metric-select">Metric</label><select id="metric-select">${state.data.metrics.map(m=>`<option value="${m.metric_id}" ${m.metric_id===state.metric?'selected':''}>${escapeHtml(m.name)}</option>`).join('')}</select></div>`;}
function timeRangeControls(){return `<div class="field"><label for="start-year">Start</label><select id="start-year">${years().map(y=>`<option ${y===state.startYear?'selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="end-year">End</label><select id="end-year">${years().map(y=>`<option ${y===state.endYear?'selected':''}>${y}</option>`).join('')}</select></div>`;}
function countryOptions(selected){return state.data.countries.map(c=>`<option value="${c.iso3}" ${selected.includes(c.iso3)?'selected':''}>${String(c.gdp_rank).padStart(2,'0')} · ${escapeHtml(c.name)}</option>`).join('');}
function years(){return Array.from({length:state.data.meta.end_year-state.data.meta.start_year+1},(_,i)=>state.data.meta.start_year+i);}
function coverage(id,iso){const n=(state.index.series.get(`${id}|${iso}`)||[]).filter(o=>o.value!=null).length;const total=state.data.meta.end_year-state.data.meta.start_year+1;return `${n}/${total} yrs`;}
function rankRow(rank,name,sub,value){return `<div class="rank-row"><span class="rank-num">${escapeHtml(rank)}</span><span class="rank-name">${escapeHtml(name)}<small>${escapeHtml(sub)}</small></span><span class="rank-value">${escapeHtml(value)}</span></div>`;}
function bind(){
 $('#metric-select')?.addEventListener('change',e=>{state.metric=e.target.value;state.page=1;syncUrl();render();});
 $('#country-select')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render();});
 $('#base-year')?.addEventListener('change',e=>{state.baseYear=+e.target.value;syncUrl();render();});
 $('#start-year')?.addEventListener('change',e=>{state.startYear=Math.min(+e.target.value,state.endYear);syncUrl();render();});
 $('#end-year')?.addEventListener('change',e=>{state.endYear=Math.max(+e.target.value,state.startYear);syncUrl();render();});
 $('#compare-countries')?.addEventListener('change',e=>{state.compare=[...e.target.selectedOptions].map(o=>o.value).slice(0,6);syncUrl();render();});
 $('#search')?.addEventListener('input',e=>{state.search=e.target.value;state.page=1;render();});
 $$('[data-page]').forEach(button=>button.addEventListener('click',()=>{state.page=+button.dataset.page;render();document.querySelector('.table-wrap')?.focus();}));
 $$('[data-go]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.go;syncUrl();render();}));
}
function drawCharts(){ $$('[data-chart="lines"]').forEach(drawLineChart); }
function drawLineChart(el){
  const renderStarted=performance.now();
  const ids=el.dataset.countries.split(',').filter(Boolean),metricId=el.dataset.metric,base=+(el.dataset.rebase||0);
  const sets=ids.map(iso=>{let rows=(state.index.series.get(`${metricId}|${iso}`)||[]).filter(o=>o.value!=null&&o.year>=state.startYear&&o.year<=state.endYear);if(base){const b=(state.index.series.get(`${metricId}|${iso}`)||[]).find(r=>r.year===base)?.value;rows=rows.map(r=>({...r,value:b?100*r.value/b:null})).filter(r=>r.value!=null);}return{iso,rows};}).filter(s=>s.rows.length);
  if(!sets.length){el.innerHTML='<div class="empty">No observations available for this selection.</div>';return;}
  const all=sets.flatMap(s=>s.rows),years=all.map(r=>r.year),vals=all.map(r=>r.value),minX=Math.min(...years),maxX=Math.max(...years),minY=Math.min(...vals),maxY=Math.max(...vals),W=800,H=310,p={l:52,r:16,t:14,b:35};
  const x=y=>p.l+(y-minX)/(maxX-minX||1)*(W-p.l-p.r), y=v=>H-p.b-(v-minY)/(maxY-minY||1)*(H-p.t-p.b);
  let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${metric(metricId).name} time series"><text x="12" y="14" class="axis-label">${base?'INDEX':metric(metricId).unit.toUpperCase()}</text>`;
  for(let i=0;i<5;i++){const val=minY+(maxY-minY)*i/4,py=y(val);svg+=`<line x1="${p.l}" y1="${py}" x2="${W-p.r}" y2="${py}" class="grid-line"/><text x="${p.l-7}" y="${py+3}" text-anchor="end" class="axis-label">${compact(val)}</text>`;}
  for(let yr=Math.ceil(minX/5)*5;yr<=maxX;yr+=5)svg+=`<text x="${x(yr)}" y="${H-10}" text-anchor="middle" class="axis-label">${yr}</text>`;
  sets.forEach((s,i)=>{const d=s.rows.map((r,j)=>`${j?'L':'M'}${x(r.year)},${y(r.value)}`).join(' ');svg+=`<path d="${d}" class="line" stroke="${colors[i]}"/>${s.rows.map(r=>`<circle cx="${x(r.year)}" cy="${y(r.value)}" r="3" fill="${colors[i]}" class="dot" data-tip="${countryMeta(s.iso).name}|${r.year}|${fmt(r.value,base?'number':metric(metricId).format)}"></circle>`).join('')}`;});
  const fallback=`<table class="sr-only"><caption>${escapeHtml(metric(metricId).name)} chart data</caption><thead><tr><th>Economy</th><th>Period</th><th>Value</th></tr></thead><tbody>${sets.flatMap(s=>s.rows.map(r=>`<tr><td>${escapeHtml(countryMeta(s.iso).name)}</td><td>${formatReferencePeriod(r.reference_period??r.year,metric(metricId).frequency)}</td><td>${r.value}</td></tr>`)).join('')}</tbody></table>`;el.innerHTML=svg+'</svg>'+fallback; $$('[data-tip]',el).forEach(dot=>{dot.addEventListener('mouseenter',showTip);dot.addEventListener('mouseleave',hideTip);});recordTiming('chart_render',renderStarted,{metric_id:metricId,series:sets.length,points:all.length});
}

function applyUrlState(){const params=new URLSearchParams(location.search);const views=['overview','rankings','compare','country','data','methodology','diagnostics'];const view=params.get('view');if(views.includes(view))state.view=view;const metricId=params.get('metric');if(metricId&&/^[a-z0-9_]+$/.test(metricId))state.metric=metricId;const country=params.get('country');if(country&&/^[A-Z]{3}$/.test(country))state.country=country;const countries=(params.get('countries')||'').split(',').filter(value=>/^[A-Z]{3}$/.test(value)).slice(0,6);if(countries.length)state.compare=countries;for(const [key,target] of [['start','startYear'],['end','endYear']]){const value=Number(params.get(key));if(Number.isInteger(value)&&value>=1800&&value<=2200)state[target]=value;}}
function syncUrl(){const params=new URLSearchParams();params.set('view',state.view);if(state.metric)params.set('metric',state.metric);if(state.view==='country')params.set('country',state.country);if(state.view==='compare')params.set('countries',state.compare.join(','));if(state.startYear)params.set('start',state.startYear);if(state.endYear)params.set('end',state.endYear);history.replaceState(null,'',`${location.pathname}?${params}`);}
function compact(v){const a=Math.abs(v);return a>=1e12?`${(v/1e12).toFixed(1)}T`:a>=1e9?`${(v/1e9).toFixed(0)}B`:a>=1e6?`${(v/1e6).toFixed(0)}M`:v.toFixed(a<10?1:0);}
function showTip(e){const [name,year,value]=e.target.dataset.tip.split('|');const tip=document.createElement('div');tip.className='tooltip';tip.id='tooltip';tip.textContent=`${name} · ${year} · ${value}`;document.body.append(tip);moveTip(e);e.target.addEventListener('mousemove',moveTip);}
function moveTip(e){const t=$('#tooltip');if(t){t.style.left=`${e.clientX}px`;t.style.top=`${e.clientY}px`;}}function hideTip(){$('#tooltip')?.remove();}
function downloadCSV(){let rows=(state.index.byMetric.get(state.metric)||[]).filter(o=>!state.search||countryMeta(o.iso3).name.toLowerCase().includes(state.search.toLowerCase()));const head=['country','iso3','reference_period','year','metric_id','metric_name','value','unit','source_id','source_dataset_id','source_indicator_id','retrieved_at','raw_snapshot_id','pipeline_run_id'];const csv=[head.join(','),...rows.map(o=>[countryMeta(o.iso3).name,o.iso3,o.reference_period??o.year,o.year,o.metric_id,metric(o.metric_id).display_name??metric(o.metric_id).name,o.value,o.unit??metric(o.metric_id).unit,o.source_id,o.source_dataset_id??'',o.source_indicator_id??o.source_indicator,o.retrieved_at,o.raw_snapshot_id??'',o.pipeline_run_id??''].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`atlas-${state.metric}.csv`;a.click();URL.revokeObjectURL(a.href);}
init();
