const state={data:null,index:null,coverage:null,loadedShards:new Set(),pendingShards:new Map(),rankings:new Map(),pendingRankings:new Map(),view:'overview',metric:'gdp_current_usd',rankingYear:null,country:'USA',compare:['USA','CHN','DEU','IND'],compareMode:'absolute',baseYear:2000,startYear:null,endYear:null,search:'',category:'all',source:'all',recency:'all',sort:'year_desc',page:1,pageSize:50,timings:[],xMetric:'gdp_per_capita_current_usd',yMetric:'gdp_growth_pct',bubbleMetric:'population',exploreYear:2025,commandIndex:0};
const colors=['var(--chart-1)','var(--chart-2)','var(--chart-3)','var(--chart-4)','var(--chart-5)','var(--chart-6)'];
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

async function init(){
  applyUrlState();const started=performance.now();
  try{const response=await fetch('data/catalog.json');if(!response.ok)throw new Error(`Catalog request failed (${response.status})`);state.data={...(await response.json()),observations:[]};recordTiming('catalog_load',started);}
  catch(error){showFatal('Catalog unavailable','The published data catalog could not be loaded.',error);return;}
  try{const response=await fetch('data/coverage.json');if(response.ok)state.coverage=await response.json();}catch(error){console.warn('[atlas:coverage]',error);}
  state.index=buildIndex();state.startYear=state.startYear||state.data.meta.start_year;state.endYear=state.endYear||state.data.meta.end_year;
  if(!state.data.countries.some(row=>row.iso3===state.country))state.country=state.data.countries[0].iso3;
  $('#freshness').textContent=`Snapshot ${shortDate(state.data.meta.generated_at)}`;$('#coverage-pill').textContent=`${state.data.meta.universe_size} economies · ${state.data.meta.reference_year} cohort`;
  $('#nav').addEventListener('click',event=>{if(!event.target.dataset.view)return;state.view=event.target.dataset.view;state.page=1;syncUrl();render();});
  $('#download-button').addEventListener('click',downloadCSV);$('#share-button').addEventListener('click',copyView);
  setupTheme();setupCommandSearch();
  window.addEventListener('popstate',()=>{applyUrlState();render();});$('#loading').hidden=true;$('#app').hidden=false;await render();
}

function buildIndex(){const metrics=new Map(),countries=new Map(),byMetric=new Map(),series=new Map(),latest=new Map(),metricMax=new Map();state.data.metrics.forEach(m=>metrics.set(m.metric_id,m));state.data.countries.forEach(c=>countries.set(c.iso3,c));for(const o of state.data.observations){if(!byMetric.has(o.metric_id))byMetric.set(o.metric_id,[]);byMetric.get(o.metric_id).push(o);const key=`${o.metric_id}|${o.iso3}`;if(!series.has(key))series.set(key,[]);series.get(key).push(o);if(o.value!=null){const current=latest.get(key);if(!current||o.year>current.year)latest.set(key,o);metricMax.set(o.metric_id,Math.max(metricMax.get(o.metric_id)||0,o.year));}}series.forEach(rows=>rows.sort((a,b)=>a.year-b.year));return{metrics,countries,byMetric,series,latest,metricMax};}
function metric(id){return state.index.metrics.get(id)}function countryMeta(iso){return state.index.countries.get(iso)}function latest(id,iso){return state.index.latest.get(`${id}|${iso}`)||null}function series(id,iso){return state.index.series.get(`${id}|${iso}`)||[]}function at(id,iso,year){return series(id,iso).find(row=>row.year===year&&row.value!=null)||null}

async function loadMetric(id){if(state.loadedShards.has(id))return;if(state.pendingShards.has(id))return state.pendingShards.get(id);const url=state.data.observation_shards[id];const promise=(async()=>{const started=performance.now(),response=await fetch(url);if(!response.ok)throw new Error(`Metric shard failed (${response.status})`);const rows=await response.json();state.data.observations.push(...rows);state.loadedShards.add(id);state.index=buildIndex();recordTiming('metric_shard_load',started,{metric_id:id,rows:rows.length});state.pendingShards.delete(id);})();state.pendingShards.set(id,promise);return promise;}
async function loadRanking(id){if(state.rankings.has(id))return state.rankings.get(id);if(state.pendingRankings.has(id))return state.pendingRankings.get(id);const promise=(async()=>{const response=await fetch(state.data.ranking_shards[id]);if(!response.ok)throw new Error(`Ranking shard failed (${response.status})`);const asset=await response.json();state.rankings.set(id,asset);state.pendingRankings.delete(id);return asset;})();state.pendingRankings.set(id,promise);return promise;}
function requiredMetrics(){if(['country','coverage','data'].includes(state.view))return state.data.metrics.map(m=>m.metric_id);if(state.view==='overview')return state.data.overview_metric_ids;if(['rankings','compare'].includes(state.view))return[state.metric];return[];}
function requiredRankings(){if(state.view==='overview')return state.data.overview_metric_ids;if(state.view==='country')return state.data.metrics.map(m=>m.metric_id);if(['rankings','compare'].includes(state.view))return[state.metric];return[];}
async function render(){try{await Promise.all(requiredMetrics().map(loadMetric));await Promise.all(requiredRankings().map(loadRanking));}catch(error){$('#app').innerHTML=errorState('Analytical asset unavailable',error.message);return;}
  $$('#nav button').forEach(button=>{const active=button.dataset.view===state.view;button.classList.toggle('active',active);button.setAttribute('aria-current',active?'page':'false')});
  const titles={overview:'Global Economy',rankings:'Rankings',compare:'Compare',country:'Economies',coverage:'Coverage',data:'Explore',methodology:'Methodology',diagnostics:'Diagnostics'};$('#page-title').textContent=titles[state.view];
  const views={overview,rankings,compare,country,coverage:coverageView,data:explorer,methodology,diagnostics};$('#app').innerHTML=views[state.view]();bind();bindProduct();drawCharts();drawProductCharts();
}

function ranking(id,year=null){const asset=state.rankings.get(id);if(!asset)return null;const selected=year||state.rankingYear||asset.default_ranking_year;return asset.rankings[String(selected)]||asset.rankings[String(asset.default_ranking_year)];}
function recency(latestYear,maxYear){if(latestYear==null)return{lag:null,status:'unavailable'};const lag=maxYear-latestYear;return{lag,status:lag===0?'current_year':lag===1?'prior_year':'historical'};}
function statusLabel(status){return({current_year:'Current year',prior_year:'Prior year',historical:'Historical',unavailable:'Unavailable'})[status]||status;}
function fmt(value,type='number',decimals){if(value==null||!Number.isFinite(Number(value)))return'—';const n=Number(value),d=decimals??(type==='percent'?1:2);if(type==='currency')return`$${abbreviate(n,d)}`;if(type==='percent')return`${n.toFixed(d)}%`;if(type==='integer')return Math.round(n).toLocaleString();return abbreviate(n,d);}
function abbreviate(n,d=2){const a=Math.abs(n);if(a>=1e12)return`${(n/1e12).toFixed(d)}T`;if(a>=1e9)return`${(n/1e9).toFixed(d)}B`;if(a>=1e6)return`${(n/1e6).toFixed(d)}M`;if(a>=1e3)return`${(n/1e3).toFixed(d)}K`;return n.toLocaleString(undefined,{maximumFractionDigits:d});}
function shortDate(value){return new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}function years(){return Array.from({length:state.data.meta.end_year-state.data.meta.start_year+1},(_,i)=>state.data.meta.start_year+i);}
function provenance(m,observation=null){return`<details class="provenance"><summary>Source & definition</summary><dl><dt>Organization</dt><dd>World Bank</dd><dt>Dataset</dt><dd>World Development Indicators</dd><dt>Indicator</dt><dd><code>${escapeHtml(m.code)}</code></dd><dt>Definition</dt><dd>${escapeHtml(m.description)}</dd><dt>Observation year</dt><dd>${observation?.year??'Varies'}</dd><dt>Retrieved</dt><dd>${observation?shortDate(observation.retrieved_at):shortDate(state.data.meta.generated_at)}</dd><dt>Release</dt><dd><code>${escapeHtml(state.data.meta.release_id)}</code></dd></dl></details>`;}
function kpi(label,value,meta,accent='#2463eb',detail=''){return`<article class="card kpi" style="--accent:${accent}"><div class="kpi-label">${escapeHtml(label)}</div><div class="kpi-value">${escapeHtml(value)}</div><div class="kpi-meta">${meta}</div>${detail}</article>`;}
function badge(status,lag){return`<span class="status status-${status}">${statusLabel(status)}${lag==null?'':` · ${lag}y lag`}</span>`;}
function metricSelect(){return`<div class="field"><label for="metric-select">Metric</label><select id="metric-select">${state.data.metrics.map(m=>`<option value="${m.metric_id}" ${m.metric_id===state.metric?'selected':''}>${escapeHtml(m.name)}</option>`).join('')}</select></div>`;}
function countryOptions(selected){return state.data.countries.map(c=>`<option value="${c.iso3}" ${selected.includes(c.iso3)?'selected':''}>${String(c.gdp_rank).padStart(2,'0')} · ${escapeHtml(c.name)}</option>`).join('');}
function rankingYearSelect(asset){const preferred=[2025,2024,2023,2020,2015,2010,2005,2000],available=asset.available_ranking_years,options=[...new Set([...preferred.filter(y=>available.includes(y)),...available])];const selected=state.rankingYear&&available.includes(state.rankingYear)?state.rankingYear:asset.default_ranking_year;return`<div class="field"><label for="ranking-year">Ranking year</label><select id="ranking-year">${options.map(y=>`<option ${y===selected?'selected':''}>${y}</option>`).join('')}</select></div>`;}

function legacyOverview(){const modules=[['gdp_current_usd','Global economy','Largest economies by nominal GDP'],['gdp_growth_pct','Fastest real growth','Common-year annual growth'],['inflation_cpi_pct','Highest inflation','Common-year CPI change'],['unemployment_pct','Lowest unemployment','Ascending common-year comparison'],['central_government_debt_pct_gdp','Central-government debt','Limited common-year coverage']];return`<div class="brief"><div><span class="eyebrow">RELEASE ${escapeHtml(state.data.meta.release_id)}</span><h2>One cohort. Comparable years. Traceable evidence.</h2><p>Every overview module uses one explicit observation year and keeps missing economies visible. Coverage is part of the result, not a footnote.</p></div><span class="source-chip"><i></i>WORLD BANK WDI</span></div><section class="overview-grid">${modules.map(([id,title,subtitle])=>overviewModule(id,title,subtitle)).join('')}</section>`;}
function overviewModule(id,title,subtitle){const asset=state.rankings.get(id),r=ranking(id,asset.default_ranking_year),m=metric(id);let rows=r.rows.filter(x=>x.rank);if(id==='unemployment_pct')rows=rows.slice().sort((a,b)=>a.value-b.value||a.iso3.localeCompare(b.iso3));rows=rows.slice(0,6);return`<article class="panel overview-module"><div class="panel-head"><div><h3>${title}</h3><div class="panel-sub">${subtitle} · ${m.unit}</div></div><span class="coverage-chip">${r.ranked_entity_count}/${r.cohort_size} · ${r.ranking_year}</span></div><div class="rank-list">${rows.map((row,i)=>rankRow(id==='unemployment_pct'?i+1:row.rank,row.country,row.iso3,fmt(row.value,m.format,m.preferred_decimals))).join('')}</div>${id==='central_government_debt_pct_gdp'?`<div class="note">${r.ranked_entity_count}/50 observed in 2024 · 35/50 have any historical observation.</div>`:''}<button class="text-button" data-open-ranking="${id}" data-ranking-year="${r.ranking_year}">Open full ranking →</button></article>`;}

function rankings(){const asset=state.rankings.get(state.metric),r=ranking(state.metric),m=metric(state.metric);state.rankingYear=r.ranking_year;return`<div class="brief"><div><span class="eyebrow">RANK WITHIN THE ATLAS ANALYTICAL COHORT</span><h2>${escapeHtml(m.name)} ranking</h2><p>Only observations from ${r.ranking_year} receive a rank. Older values appear separately as historical context and never enter the ranking.</p></div><div class="ranking-summary"><strong>Ranking year: ${r.ranking_year}</strong><span>Coverage: ${r.ranked_entity_count} / ${r.cohort_size} economies</span></div></div><div class="controls">${metricSelect()}${rankingYearSelect(asset)}<div class="field"><label for="search">Search economy</label><input id="search" value="${escapeHtml(state.search)}" placeholder="United, Korea, Brazil"></div></div>${rankingTable(r,m)}<section class="panel rank-history-panel"><div class="panel-head"><div><h3>Country rank history</h3><div class="panel-sub">Rank within the Atlas analytical cohort · exact-year observations only</div></div><select id="rank-country">${countryOptions([state.country])}</select></div><div class="chart" data-chart="rank-history" data-metric="${state.metric}" data-country="${state.country}"></div></section>`;}
function legacyRankingTable(r,m){const query=state.search.toLowerCase(),rows=r.rows.filter(row=>!query||`${row.country} ${row.iso3}`.toLowerCase().includes(query));return`<div class="table-wrap"><table><caption class="sr-only">${escapeHtml(m.name)} ranking for ${r.ranking_year}</caption><thead><tr><th>Rank</th><th>Economy</th><th class="num">Value</th><th>Observation year</th><th>${changeLabel(m,1)}</th><th>Latest historical context</th><th>Recency</th><th>Source</th></tr></thead><tbody>${rows.map(row=>{const change=row.changes?.['1'];return`<tr class="${row.rank?'':'row-missing'}"><td class="num">${row.rank??'—'}</td><th class="country-cell">${escapeHtml(row.country)}<small>${row.iso3}</small></th><td class="num">${row.value==null?`Not available for ${r.ranking_year}`:fmt(row.value,m.format,m.preferred_decimals)}</td><td>${row.observation_year??'—'}</td><td class="num">${formatChange(change,m)}</td><td>${row.value==null&&row.latest_historical_year?`${fmt(row.latest_historical_value,m.format,m.preferred_decimals)} · ${row.latest_historical_year}`:'—'}</td><td>${badge(row.recency_status,row.lag_years)}</td><td><span class="micro">WDI / ${escapeHtml(m.code)}</span></td></tr>`}).join('')}</tbody></table></div>${provenance(m)}`;}
function changeLabel(m,window){return m.change_transformation==='percentage_point_change'?`${window}-year pp change`:`${window}-year CAGR`;}
function formatChange(value,m){if(value==null)return'—';const suffix=m.change_transformation==='percentage_point_change'?' pp':'%';return`${value>0?'+':''}${value.toFixed(1)}${suffix}`;}

function legacyCompare(){const selected=state.compare.filter(countryMeta),m=metric(state.metric),canIndex=m.indexing_allowed,stateMode=canIndex?state.compareMode:'absolute';return`<div class="brief"><div><span class="eyebrow">TRAJECTORY COMPARISON</span><h2>Compare economies on one analytical scale.</h2><p>Absolute values preserve the metric’s native unit. Indexed trajectories set each selected economy’s observed base-year value to 100; they do not change the underlying metric definition.</p></div></div><div class="controls"><div class="field"><label for="compare-countries">Economies</label><select id="compare-countries" multiple size="5">${countryOptions(selected)}</select></div>${metricSelect()}${canIndex?`<div class="field"><label for="compare-mode">Display</label><select id="compare-mode"><option value="absolute" ${stateMode==='absolute'?'selected':''}>Absolute values</option><option value="indexed" ${stateMode==='indexed'?'selected':''}>Indexed trajectory</option></select></div><div class="field"><label for="base-year">Index start year</label><select id="base-year">${years().map(y=>`<option ${y===state.baseYear?'selected':''}>${y}</option>`).join('')}</select></div>`:''}${timeRangeControls()}</div>${!canIndex?'<div class="note">Indexing is not enabled for this rate/share metric. Use absolute values in the declared unit.</div>':''}<section class="panel"><div class="panel-head"><div><h3>${escapeHtml(m.name)} trajectories</h3><div class="panel-sub">${stateMode==='indexed'?`Selected start year ${state.baseYear} = 100`:`${m.unit} · ${state.startYear}-${state.endYear}`}</div></div><div class="legend">${selected.map((iso,i)=>`<span><i style="background:${colors[i]}"></i>${escapeHtml(countryMeta(iso).name)}</span>`).join('')}</div></div><div class="chart" data-chart="lines" data-metric="${state.metric}" data-countries="${selected}" data-rebase="${stateMode==='indexed'?state.baseYear:''}"></div>${provenance(m)}</section>`;}
function timeRangeControls(){return`<div class="field"><label for="start-year">Start</label><select id="start-year">${years().map(y=>`<option ${y===state.startYear?'selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="end-year">End</label><select id="end-year">${years().map(y=>`<option ${y===state.endYear?'selected':''}>${y}</option>`).join('')}</select></div>`;}

function legacyCountry(){const c=countryMeta(state.country),ids=state.data.metrics.map(m=>m.metric_id);return`<div class="controls"><div class="field"><label for="country-select">Economy</label><select id="country-select">${countryOptions([state.country])}</select></div></div><section class="country-hero"><div><span class="eyebrow">${escapeHtml(c.region)} · ${escapeHtml(c.income_group)}</span><h2>${escapeHtml(c.name)}</h2><p>${c.iso3} · approved Atlas cohort · eligibility ${c.analytical_eligibility}</p></div><div class="hero-rank"><span class="micro">NOMINAL GDP RANK · ${c.reference_year}</span><strong>#${String(c.gdp_rank).padStart(2,'0')}</strong></div></section><h3 class="section-title">Snapshot</h3><section class="kpis kpis-wide">${ids.map((id,i)=>countryMetricCard(id,c.iso3,colors[i%colors.length])).join('')}</section><h3 class="section-title">Historical performance</h3><section class="history-grid">${ids.filter(id=>id!=='population').map(id=>{const m=metric(id);return`<article class="panel compact-chart"><div class="panel-head"><div><h3>${escapeHtml(m.name)}</h3><div class="panel-sub">${m.unit} · observed values only</div></div></div><div class="chart" data-chart="lines" data-metric="${id}" data-countries="${c.iso3}"></div></article>`}).join('')}</section><h3 class="section-title">Relative position</h3>${relativeTable(c.iso3)}<h3 class="section-title">Data coverage</h3>${countryCoverage(c.iso3)}`;}
function countryMetricCard(id,iso,accent){const m=metric(id),o=latest(id,iso),max=state.index.metricMax.get(id),fresh=recency(o?.year,max),r=ranking(id,max),row=r?.rows.find(x=>x.iso3===iso);return kpi(m.name,o?fmt(o.value,m.format,m.preferred_decimals):'Not available',`${o?`Observed ${o.year}`:'No observation'} · ${badge(fresh.status,fresh.lag)}${row?.rank?`<br>Rank ${row.rank}/${r.ranked_entity_count} in ${r.ranking_year}`:''}`,accent,provenance(m,o));}
function relativeTable(iso){return`<div class="table-wrap"><table><thead><tr><th>Metric</th><th>Ranking year</th><th>Rank</th><th>Coverage</th><th class="num">Country value</th><th class="num">Cohort median</th><th>${changeLabel({change_transformation:'cagr'},5)} / pp</th><th>10-year change</th></tr></thead><tbody>${state.data.metrics.map(m=>{const asset=state.rankings.get(m.metric_id),r=ranking(m.metric_id,asset.default_ranking_year),row=r.rows.find(x=>x.iso3===iso),values=r.rows.filter(x=>x.value!=null).map(x=>x.value).sort((a,b)=>a-b),med=values.length?values[Math.floor(values.length/2)]:null;return`<tr><th>${escapeHtml(m.name)}</th><td>${r.ranking_year}</td><td>${row.rank??'—'}</td><td>${r.ranked_entity_count}/${r.cohort_size}</td><td class="num">${fmt(row.value,m.format,m.preferred_decimals)}</td><td class="num">${fmt(med,m.format,m.preferred_decimals)}</td><td class="num">${formatChange(row.changes?.['5'],m)}</td><td class="num">${formatChange(row.changes?.['10'],m)}</td></tr>`}).join('')}</tbody></table></div>`;}
function countryCoverage(iso){const rows=state.coverage?.country_metric?.filter(row=>row.iso3===iso)||[];return`<div class="coverage coverage-detailed">${state.data.metrics.map(m=>{const row=rows.find(x=>x.metric_id===m.metric_id)||{observation_count:0,earliest_year:null,latest_year:null,recency_status:'unavailable',lag_years:null};return`<article class="coverage-cell"><b>${escapeHtml(m.name)}</b><span>${row.observation_count} observations</span><span>${row.earliest_year??'—'}–${row.latest_year??'—'}</span>${badge(row.recency_status,row.lag_years)}</article>`}).join('')}</div>`;}

function coverageView(){const rows=state.coverage?.country_metric||[];return`<div class="brief"><div><span class="eyebrow">DATA AVAILABILITY</span><h2>Coverage is part of the evidence.</h2><p>Inspect country × metric availability, observation spans, and structural recency relative to each metric’s maximum year.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label for="recency-filter">Recency</label><select id="recency-filter"><option value="all">All statuses</option>${['current_year','prior_year','historical','unavailable'].map(x=>`<option value="${x}" ${state.recency===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></div><div class="field"><label for="search">Search economy</label><input id="search" value="${escapeHtml(state.search)}"></div></div><div class="coverage-summary">${state.coverage.inventory.map(row=>kpi(row.display_name,`${row.ranking_year_observed_country_count}/50`,`Observed in ${row.ranking_year} · ${row.ever_observed_country_count}/50 ever observed`)).join('')}</div>${coverageTable(rows)}`;}
function coverageTable(rows){const query=state.search.toLowerCase();const filtered=rows.filter(row=>row.metric_id===state.metric&&(!query||`${row.country} ${row.iso3}`.toLowerCase().includes(query))&&(state.recency==='all'||row.recency_status===state.recency));return`<div class="table-wrap"><table><thead><tr><th>Economy</th><th>Metric</th><th>Earliest</th><th>Latest</th><th>Observations</th><th>Metric maximum</th><th>Lag</th><th>Status</th></tr></thead><tbody>${filtered.map(row=>`<tr><th class="country-cell">${escapeHtml(row.country)}<small>${row.iso3}</small></th><td>${escapeHtml(metric(row.metric_id).name)}</td><td>${row.earliest_year??'—'}</td><td>${row.latest_year??'—'}</td><td>${row.observation_count}</td><td>${row.metric_max_year??'—'}</td><td>${row.lag_years??'—'}</td><td>${badge(row.recency_status,row.lag_years)}</td></tr>`).join('')}</tbody></table></div>`;}

function legacyExplorer(){const all=filteredExplorerRows(),pages=Math.max(1,Math.ceil(all.length/state.pageSize));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*state.pageSize,state.page*state.pageSize);return`<div class="brief"><div><span class="eyebrow">CANONICAL OBSERVATIONS</span><h2>Filter, inspect, and export the evidence layer.</h2><p>Filtered exports preserve source, observation period, retrieval timestamp, raw snapshot, and pipeline lineage.</p></div></div><div class="controls">${metricSelect()}<div class="field"><label for="category-filter">Category</label><select id="category-filter"><option value="all">All categories</option>${[...new Set(state.data.metrics.map(m=>m.category))].map(x=>`<option ${state.category===x?'selected':''}>${escapeHtml(x)}</option>`).join('')}</select></div><div class="field"><label for="source-filter">Source</label><select id="source-filter"><option value="all">All sources</option>${state.data.sources.map(x=>`<option value="${x.source_id}" ${state.source===x.source_id?'selected':''}>${escapeHtml(x.name)}</option>`).join('')}</select></div><div class="field"><label for="recency-filter">Recency</label><select id="recency-filter"><option value="all">All statuses</option>${['current_year','prior_year','historical'].map(x=>`<option value="${x}" ${state.recency===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></div><div class="field"><label for="search">Country</label><input id="search" value="${escapeHtml(state.search)}" placeholder="Country or ISO3"></div>${timeRangeControls()}<div class="field"><label for="sort-select">Sort</label><select id="sort-select"><option value="year_desc" ${state.sort==='year_desc'?'selected':''}>Newest first</option><option value="country" ${state.sort==='country'?'selected':''}>Country</option><option value="value_desc" ${state.sort==='value_desc'?'selected':''}>Value high–low</option></select></div></div><div class="table-wrap"><table><thead><tr><th>Economy</th><th>Year</th><th>Metric</th><th class="num">Value</th><th>Recency</th><th>Indicator</th><th>Retrieved</th></tr></thead><tbody>${rows.map(o=>{const m=metric(o.metric_id),fresh=recency(o.year,state.index.metricMax.get(o.metric_id));return`<tr><th class="country-cell">${escapeHtml(countryMeta(o.iso3).name)}<small>${o.iso3}</small></th><td>${o.year}</td><td>${escapeHtml(m.name)}</td><td class="num">${fmt(o.value,m.format,m.preferred_decimals)}</td><td>${badge(fresh.status,fresh.lag)}</td><td><code>${escapeHtml(o.source_indicator_id)}</code></td><td>${shortDate(o.retrieved_at)}</td></tr>`}).join('')}</tbody></table></div><div class="pagination"><button data-page="${state.page-1}" ${state.page===1?'disabled':''}>Previous</button><span>Page ${state.page} of ${pages} · ${all.length.toLocaleString()} observations</span><button data-page="${state.page+1}" ${state.page===pages?'disabled':''}>Next</button></div>`;}
function filteredExplorerRows(){const query=state.search.toLowerCase();let rows=(state.index.byMetric.get(state.metric)||[]).filter(o=>o.year>=state.startYear&&o.year<=state.endYear&&(!query||`${countryMeta(o.iso3).name} ${o.iso3}`.toLowerCase().includes(query))&&(state.category==='all'||metric(o.metric_id).category===state.category)&&(state.source==='all'||o.source_id===state.source));if(state.recency!=='all')rows=rows.filter(o=>recency(o.year,state.index.metricMax.get(o.metric_id)).status===state.recency);return rows.slice().sort(state.sort==='country'?(a,b)=>a.iso3.localeCompare(b.iso3)||b.year-a.year:state.sort==='value_desc'?(a,b)=>b.value-a.value:bYear);}
function bYear(a,b){return b.year-a.year||a.iso3.localeCompare(b.iso3)}

function legacyMethodology(){return`<div class="method"><section><span class="eyebrow">ANALYTICAL COHORT</span><h3>Explicit eligibility, source-neutral universe architecture</h3><p>GDP ranking uses a common ${state.data.meta.reference_year} World Bank observation year for source-covered candidates. The candidate universe follows eligibility policy <code>${escapeHtml(state.data.meta.eligibility_policy_version)}</code> and may exclude entities unavailable from the GDP source. The current provider is <code>${escapeHtml(state.data.meta.universe_provider_id)}</code>; an approved provider/registry change can supply a normalized IMF WEO GDP series without rewriting selection logic.</p></section><section><span class="eyebrow">SAME-YEAR RANKING</span><h3>No historical fallback enters a rank</h3><p>Each ranking declares one year. Only observations in that exact year receive sequential ranks; ties resolve by ISO3. Missing economies remain visible and may show a separately labelled latest historical value.</p></section><section><span class="eyebrow">OBSERVATION RECENCY</span><h3>Structural status, not a quality score</h3><p>Annual recency is measured against each metric’s maximum year: current year (lag 0), prior year (lag 1), historical (lag 2+), or unavailable. Retrieval date never substitutes for observation year.</p></section><section><span class="eyebrow">MISSING DATA</span><h3>Published observations only</h3><p>No interpolation, carry-forward, or modeled ranking fallback is used. Current-dollar metrics remain current-dollar metrics; indexing changes the visual comparison scale, not the economic definition.</p></section><section><span class="eyebrow">SOURCE REGISTRY</span><h3>World Bank — World Development Indicators</h3><p>Primary multilateral source · CC BY 4.0 · retrieved ${shortDate(state.data.meta.generated_at)}. <a href="${state.data.sources[0].url}" target="_blank" rel="noreferrer">Open source documentation ↗</a></p></section>${state.data.metrics.map(m=>`<section><span class="eyebrow">${m.code} · ${m.family.toUpperCase()}</span><h3>${escapeHtml(m.name)}</h3><p>${escapeHtml(m.description)}</p><p><b>Unit:</b> ${escapeHtml(m.unit)}. <b>Frequency:</b> ${m.frequency}. <b>Change method:</b> ${escapeHtml(m.change_transformation)}. <b>Caveat:</b> ${escapeHtml(m.caveats)}</p></section>`).join('')}</div>`;}
function diagnostics(){const meta=state.data.meta;return`<div class="brief"><div><h2>Build diagnostics</h2><p>Operational metadata only; no economic quality judgment.</p></div></div><section class="kpis">${kpi('Data release',meta.release_id,`Pipeline ${meta.pipeline_run_id}`)}${kpi('Eligibility policy',meta.eligibility_policy_version,`${meta.universe_provider_id} provider`)}${kpi('Loaded metrics',`${state.loadedShards.size}/${state.data.metrics.length}`,`${state.data.observations.length.toLocaleString()} observations`)}${kpi('Candidate completeness',meta.candidate_universe_complete?'Complete':'Limited','Taiwan/source-unavailable disclosure')}</section>`;}

function rankRow(rank,name,sub,value){return`<div class="rank-row"><span class="rank-num">${rank}</span><span class="rank-name">${escapeHtml(name)}<small>${escapeHtml(sub)}</small></span><span class="rank-value">${escapeHtml(value)}</span></div>`;}
function errorState(title,message){return`<section class="panel empty-state" role="alert"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(message)}</p></section>`}function showFatal(title,message,error){$('#loading').innerHTML=errorState(title,message);console.error('[atlas:fatal]',error)}function recordTiming(name,started,detail={}){state.timings.push({name,duration_ms:+(performance.now()-started).toFixed(1),...detail});}

function bind(){
  $('#metric-select')?.addEventListener('change',e=>{state.metric=e.target.value;state.rankingYear=null;state.page=1;syncUrl();render()});
  $('#ranking-year')?.addEventListener('change',e=>{state.rankingYear=+e.target.value;syncUrl();render()});
  $('#country-select')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render()});$('#rank-country')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render()});
  $('#compare-countries')?.addEventListener('change',e=>{state.compare=[...e.target.selectedOptions].map(o=>o.value).slice(0,6);syncUrl();render()});$('#compare-mode')?.addEventListener('change',e=>{state.compareMode=e.target.value;syncUrl();render()});$('#base-year')?.addEventListener('change',e=>{state.baseYear=+e.target.value;syncUrl();render()});
  $('#start-year')?.addEventListener('change',e=>{state.startYear=Math.min(+e.target.value,state.endYear);state.page=1;syncUrl();render()});$('#end-year')?.addEventListener('change',e=>{state.endYear=Math.max(+e.target.value,state.startYear);state.page=1;syncUrl();render()});
  $('#search')?.addEventListener('input',e=>{state.search=e.target.value;state.page=1;render()});$('#category-filter')?.addEventListener('change',e=>{state.category=e.target.value;state.page=1;syncUrl();render()});$('#source-filter')?.addEventListener('change',e=>{state.source=e.target.value;state.page=1;syncUrl();render()});$('#recency-filter')?.addEventListener('change',e=>{state.recency=e.target.value;state.page=1;syncUrl();render()});$('#sort-select')?.addEventListener('change',e=>{state.sort=e.target.value;syncUrl();render()});
  $$('[data-page]').forEach(button=>button.addEventListener('click',()=>{state.page=+button.dataset.page;render()}));$$('[data-open-ranking]').forEach(button=>button.addEventListener('click',()=>{state.metric=button.dataset.openRanking;state.rankingYear=+button.dataset.rankingYear;state.view='rankings';syncUrl();render()}));
}
function drawCharts(){$$('[data-chart="lines"]').forEach(drawLineChart);$$('[data-chart="rank-history"]').forEach(drawRankHistory);}
function drawLineChart(el){const started=performance.now(),ids=el.dataset.countries.split(',').filter(Boolean),metricId=el.dataset.metric,base=+(el.dataset.rebase||0),m=metric(metricId);const sets=ids.map(iso=>{let rows=series(metricId,iso).filter(o=>o.value!=null&&o.year>=state.startYear&&o.year<=state.endYear);if(base){const baseValue=at(metricId,iso,base)?.value;rows=rows.map(row=>({...row,value:baseValue?row.value/baseValue*100:null})).filter(row=>row.value!=null);}return{iso,rows}}).filter(set=>set.rows.length);renderLine(el,sets,base?'Index, selected start year = 100':m.unit,started,metricId);}
function drawRankHistory(el){const asset=state.rankings.get(el.dataset.metric),iso=el.dataset.country,rows=asset.available_ranking_years.slice().sort((a,b)=>a-b).map(year=>{const row=asset.rankings[String(year)].rows.find(x=>x.iso3===iso);return row?.rank?{year,value:row.rank}:null}).filter(Boolean);renderLine(el,[{iso,rows}],`Rank within Atlas cohort · 1 is highest`,performance.now(),el.dataset.metric,true);}
function renderLine(el,sets,label,started,metricId,invert=false){if(!sets.length){el.innerHTML='<div class="empty">No observed values for this selection.</div>';return}const all=sets.flatMap(s=>s.rows),xs=all.map(r=>r.year),ys=all.map(r=>r.value),minX=Math.min(...xs),maxX=Math.max(...xs),minY=invert?1:Math.min(...ys),maxY=Math.max(...ys),W=820,H=300,p={l:58,r:18,t:24,b:36},x=v=>p.l+(v-minX)/(maxX-minX||1)*(W-p.l-p.r),y=v=>p.t+(invert?(v-minY):(maxY-v))/(maxY-minY||1)*(H-p.t-p.b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${escapeHtml(metric(metricId).name)} chart"><text x="8" y="13" class="axis-label">${escapeHtml(label.toUpperCase())}</text>`;for(let i=0;i<5;i++){const val=minY+(maxY-minY)*i/4,py=y(val);svg+=`<line x1="${p.l}" y1="${py}" x2="${W-p.r}" y2="${py}" class="grid-line"/><text x="${p.l-8}" y="${py+3}" text-anchor="end" class="axis-label">${invert?Math.round(val):compact(val)}</text>`}for(let yr=Math.ceil(minX/5)*5;yr<=maxX;yr+=5)svg+=`<text x="${x(yr)}" y="${H-10}" text-anchor="middle" class="axis-label">${yr}</text>`;sets.forEach((set,i)=>{const d=set.rows.map((r,j)=>`${j?'L':'M'}${x(r.year)},${y(r.value)}`).join(' ');svg+=`<path d="${d}" class="line" stroke="${colors[i]}"/>${set.rows.map(r=>`<circle cx="${x(r.year)}" cy="${y(r.value)}" r="3" fill="${colors[i]}" class="dot"><title>${escapeHtml(countryMeta(set.iso).name)} · ${r.year} · ${invert?`Rank ${r.value}`:fmt(r.value,metric(metricId).format)}</title></circle>`).join('')}`});el.innerHTML=svg+'</svg>';recordTiming('chart_render',started,{metric_id:metricId,points:all.length});}
function compact(v){const a=Math.abs(v);return a>=1e12?`${(v/1e12).toFixed(1)}T`:a>=1e9?`${(v/1e9).toFixed(0)}B`:a>=1e6?`${(v/1e6).toFixed(0)}M`:v.toFixed(a<10?1:0);}

function applyUrlState(){const params=new URLSearchParams(location.search),views=['overview','rankings','compare','country','coverage','data','methodology','diagnostics'];if(views.includes(params.get('view')))state.view=params.get('view');if(/^[a-z0-9_]+$/.test(params.get('metric')||''))state.metric=params.get('metric');if(/^[a-z0-9_]+$/.test(params.get('x')||''))state.xMetric=params.get('x');if(/^[a-z0-9_]+$/.test(params.get('y')||''))state.yMetric=params.get('y');if(/^(none|gdp_current_usd|population)$/.test(params.get('bubble')||''))state.bubbleMetric=params.get('bubble');if(/^[A-Z]{3}$/.test(params.get('country')||''))state.country=params.get('country');const compare=(params.get('countries')||'').split(',').filter(x=>/^[A-Z]{3}$/.test(x)).slice(0,6);if(compare.length)state.compare=compare;for(const[key,target]of[['year','rankingYear'],['base','baseYear'],['start','startYear'],['end','endYear'],['exploreYear','exploreYear']]){const value=+params.get(key);if(Number.isInteger(value)&&value>=1900&&value<=2200)state[target]=value}if(['absolute','indexed','rank','change'].includes(params.get('mode')))state.compareMode=params.get('mode');state.search=params.get('q')||'';state.category=params.get('category')||'all';state.source=params.get('source')||'all';state.recency=params.get('recency')||'all';state.sort=params.get('sort')||'year_desc';}
function syncUrl(){const params=new URLSearchParams({view:state.view,metric:state.metric});if(state.rankingYear)params.set('year',state.rankingYear);if(state.view==='country'||state.view==='rankings'||state.view==='data')params.set('country',state.country);if(state.view==='compare'){params.set('countries',state.compare.join(','));params.set('mode',state.compareMode);params.set('base',state.baseYear)}if(state.view==='data'){params.set('x',state.xMetric);params.set('y',state.yMetric);params.set('bubble',state.bubbleMetric);params.set('exploreYear',state.exploreYear)}if(state.startYear)params.set('start',state.startYear);if(state.endYear)params.set('end',state.endYear);if(state.search)params.set('q',state.search);if(state.category!=='all')params.set('category',state.category);if(state.source!=='all')params.set('source',state.source);if(state.recency!=='all')params.set('recency',state.recency);if(state.sort!=='year_desc')params.set('sort',state.sort);history.pushState(null,'',`${location.pathname}?${params}`);}
async function copyView(){await navigator.clipboard.writeText(location.href);const button=$('#share-button');button.textContent='Copied';setTimeout(()=>button.textContent='Copy view',1500);}
function downloadCSV(){const rows=filteredExplorerRows(),head=['country','iso3','year','metric_id','metric_name','value','unit','recency_status','lag_years','source_id','source_dataset_id','source_indicator_id','retrieved_at','raw_snapshot_id','raw_record_index','pipeline_run_id','release_id'],csv=[head.join(','),...rows.map(o=>{const m=metric(o.metric_id),fresh=recency(o.year,state.index.metricMax.get(o.metric_id));return[countryMeta(o.iso3).name,o.iso3,o.year,o.metric_id,m.name,o.value,o.unit,fresh.status,fresh.lag,o.source_id,o.source_dataset_id,o.source_indicator_id,o.retrieved_at,o.raw_snapshot_id,o.raw_record_index,o.pipeline_run_id,state.data.meta.release_id].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')})].join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`atlas-${state.metric}-${state.startYear}-${state.endYear}.csv`;link.click();URL.revokeObjectURL(link.href);}

function rankMovement(metricId,iso,year,window){const asset=state.rankings.get(metricId),current=asset?.rankings[String(year)]?.rows.find(x=>x.iso3===iso)?.rank,prior=asset?.rankings[String(year-window)]?.rows.find(x=>x.iso3===iso)?.rank;if(!current||!prior)return'—';const delta=prior-current;return delta===0?'No change':`${delta>0?'↑':'↓'} ${Math.abs(delta)}`;}
function rankingTable(r,m){const query=state.search.toLowerCase(),rows=r.rows.filter(row=>!query||`${row.country} ${row.iso3}`.toLowerCase().includes(query));return`<div class="table-wrap"><table><caption class="sr-only">${escapeHtml(m.name)} ranking for ${r.ranking_year}</caption><thead><tr><th>Rank</th><th>Economy</th><th class="num">Value</th><th>${changeLabel(m,1)}</th><th>Rank vs 5y</th><th>Rank vs 10y</th><th>Observation</th><th>Coverage state</th><th>Latest context</th></tr></thead><tbody>${rows.map(row=>`<tr class="${row.rank?'':'row-missing'}"><td class="num">${row.rank??'—'}</td><th class="country-cell">${escapeHtml(row.country)}<small>${row.iso3}</small></th><td class="num">${row.value==null?'—':fmt(row.value,m.format,m.preferred_decimals)}</td><td class="num">${formatChange(row.changes?.['1'],m)}</td><td>${row.rank?rankMovement(m.metric_id,row.iso3,r.ranking_year,5):'—'}</td><td>${row.rank?rankMovement(m.metric_id,row.iso3,r.ranking_year,10):'—'}</td><td>${row.observation_year??`No ${r.ranking_year} observation`}</td><td>${badge(row.recency_status,row.lag_years)}</td><td>${row.value==null&&row.latest_historical_year?`${fmt(row.latest_historical_value,m.format,m.preferred_decimals)} · ${row.latest_historical_year}`:'—'}</td></tr>`).join('')}</tbody></table></div>${provenance(m)}`;}
function setupTheme(){let saved=null;try{saved=localStorage.getItem('atlas-theme')}catch{}const preferred=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.dataset.theme=saved||preferred;$('#theme-button').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('atlas-theme',next)}catch{}});}
function commandItems(query=''){const q=query.trim().toLowerCase(),items=[];state.data.countries.forEach(c=>items.push({icon:'EC',label:c.name,meta:`${c.iso3} · Economy profile`,action:()=>go('country',{country:c.iso3})}));state.data.metrics.forEach(m=>{items.push({icon:'MX',label:m.name,meta:'Open ranking',action:()=>go('rankings',{metric:m.metric_id})});items.push({icon:'EX',label:`Explore ${m.name}`,meta:'Analytical explorer',action:()=>go('data',{metric:m.metric_id})})});[['Overview','overview'],['Compare economies','compare'],['Coverage','coverage'],['Methodology','methodology']].forEach(([label,view])=>items.push({icon:'→',label,meta:'Atlas page',action:()=>go(view)}));if(q.startsWith('compare ')){const matches=state.data.countries.filter(c=>q.includes(c.name.toLowerCase())||q.split(/\s+/).includes(c.iso3.toLowerCase())).slice(0,6);if(matches.length>=2)items.unshift({icon:'⇄',label:`Compare ${matches.map(c=>c.name).join(' and ')}`,meta:'Open comparison',action:()=>{state.compare=matches.map(c=>c.iso3);go('compare')}})}return items.filter(x=>!q||`${x.label} ${x.meta}`.toLowerCase().includes(q)||q.split(/\s+/).every(term=>`${x.label} ${x.meta}`.toLowerCase().includes(term))).slice(0,10);}
function setupCommandSearch(){const dialog=$('#command-dialog'),input=$('#command-input'),results=$('#command-results');const paint=()=>{const items=commandItems(input.value);state.commandItems=items;state.commandIndex=Math.min(state.commandIndex,Math.max(0,items.length-1));results.innerHTML=items.map((x,i)=>`<button type="button" class="command-result ${i===state.commandIndex?'active':''}" data-command="${i}" role="option" aria-selected="${i===state.commandIndex}"><b>${x.icon}</b><span>${escapeHtml(x.label)}<small>${escapeHtml(x.meta)}</small></span><span>↵</span></button>`).join('')||'<div class="empty">No matching Atlas destination.</div>';$$('[data-command]',results).forEach(button=>button.addEventListener('click',()=>{items[+button.dataset.command].action();dialog.close()}));};const open=()=>{dialog.showModal();input.value='';state.commandIndex=0;paint();input.focus()};$('#command-button').addEventListener('click',open);document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();open()}});input.addEventListener('input',()=>{state.commandIndex=0;paint()});input.addEventListener('keydown',event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();state.commandIndex=(state.commandIndex+(event.key==='ArrowDown'?1:-1)+state.commandItems.length)%state.commandItems.length;paint()}if(event.key==='Enter'&&state.commandItems[state.commandIndex]){event.preventDefault();state.commandItems[state.commandIndex].action();dialog.close()}});}
function go(view,updates={}){Object.assign(state,updates,{view});state.rankingYear=null;syncUrl();render();}
function trustStrip(){return`<div class="trust-strip"><span>Source-backed</span><span>Observation-year aware</span><span>No silent interpolation</span><span>Versioned release</span><span>Reproducible methodology</span></div>`;}
function overview(){const gdp=ranking('gdp_current_usd'),total=gdp.rows.reduce((sum,row)=>sum+(row.value||0),0),growth=ranking('gdp_growth_pct'),inflation=ranking('inflation_cpi_pct'),debt=ranking('central_government_debt_pct_gdp');return`<div class="brief"><div><span class="eyebrow">ATLAS DATA RELEASE · ${shortDate(state.data.meta.generated_at)}</span><h2>Global Economy</h2><p>The structure, momentum, and coverage of the world's largest economies—using comparable observation years and traceable source data.</p></div><div class="ranking-summary"><strong>${gdp.ranking_year} economic structure</strong><span>${gdp.ranked_entity_count}/50 economies · World Bank WDI</span></div></div>${trustStrip()}<section class="world-hero"><article class="panel world-structure"><div class="panel-head"><div><h3>Structure of global output</h3><div class="panel-sub">Area represents nominal GDP · ${gdp.ranking_year}</div></div><button class="chart-action" data-open-ranking="gdp_current_usd" data-ranking-year="${gdp.ranking_year}">View ranking</button></div><div class="treemap" data-chart="treemap" aria-label="Nominal GDP treemap"></div></article><aside class="hero-aside"><article class="card hero-stat"><span class="eyebrow">ATLAS COHORT OUTPUT</span><strong>${fmt(total,'currency',1)}</strong><span class="micro">Sum of 50 observed economies · ${gdp.ranking_year}</span></article><article class="card hero-stat"><span class="eyebrow">GROWTH LEADER</span><strong>${escapeHtml(growth.rows[0].country)}</strong><span class="micro">${fmt(growth.rows[0].value,'percent',1)} · ${growth.ranking_year}</span></article><article class="card hero-stat"><span class="eyebrow">INFLATION COVERAGE</span><strong>${inflation.ranked_entity_count}/50</strong><span class="micro">Comparable ${inflation.ranking_year} observations</span></article></aside></section><section class="overview-grid">${overviewModule('gdp_growth_pct','Growth','Fastest real GDP growth')}${overviewModule('inflation_cpi_pct','Prices','Highest CPI inflation')}${overviewModule('unemployment_pct','Labor','Lowest unemployment')}${overviewModule('central_government_debt_pct_gdp','Fiscal','Central-government debt')}</section><section class="panel" style="margin-top:16px"><div class="panel-head"><div><h3>Inflation distribution</h3><div class="panel-sub">Position of observed economies · median marked · ${inflation.ranking_year}</div></div><span class="coverage-chip">${inflation.ranked_entity_count}/50 observed</span></div><div class="distribution" data-chart="distribution" data-metric="inflation_cpi_pct"></div>${provenance(metric('inflation_cpi_pct'))}</section>`;}
function treemap(){const r=ranking('gdp_current_usd'),rows=r.rows.filter(x=>x.value),total=rows.reduce((s,x)=>s+x.value,0),el=$('[data-chart="treemap"]');if(!el)return;el.innerHTML=rows.slice(0,30).map((row,i)=>{const share=row.value/total,span=Math.max(1,Math.min(12,Math.round(Math.sqrt(share)*12))),height=Math.max(1,Math.min(4,Math.round(Math.sqrt(share)*7)));return`<button class="tree-node" style="grid-column:span ${span};grid-row:span ${height};opacity:${Math.max(.55,1-i*.012)}" data-country-link="${row.iso3}" aria-label="${escapeHtml(row.country)}, ${fmt(row.value,'currency',1)}, rank ${row.rank}, ${(share*100).toFixed(1)} percent of cohort"><b>${escapeHtml(row.country)}</b><small>${fmt(row.value,'currency',1)} · ${(share*100).toFixed(1)}%</small></button>`}).join('');}
function distributionChart(){const el=$('[data-chart="distribution"]');if(!el)return;const id=el.dataset.metric,r=ranking(id),rows=r.rows.filter(x=>x.value).sort((a,b)=>a.value-b.value),min=rows[0].value,max=rows.at(-1).value,med=rows[Math.floor(rows.length/2)].value,pos=v=>(v-min)/(max-min||1)*100;el.innerHTML=`<span class="distribution-label" style="left:${pos(med)}%">Median ${fmt(med,metric(id).format,1)}</span><i class="distribution-median" style="left:${pos(med)}%"></i>${rows.map(row=>`<button class="distribution-dot ${row.iso3===state.country?'selected':''}" style="left:${pos(row.value)}%" data-country-link="${row.iso3}" aria-label="${escapeHtml(row.country)} ${fmt(row.value,metric(id).format,1)}"></button>`).join('')}`;}
function dataHighlights(iso){const c=countryMeta(iso),gdp=series('gdp_current_usd',iso).filter(x=>x.value),latestGdp=gdp.at(-1),base=gdp.find(x=>x.year===2000),peak=gdp.reduce((a,b)=>a.value>b.value?a:b),rankAsset=state.rankings.get('gdp_current_usd'),nowRank=rankAsset.rankings[String(rankAsset.default_ranking_year)].rows.find(x=>x.iso3===iso)?.rank,oldRank=rankAsset.rankings['2000']?.rows.find(x=>x.iso3===iso)?.rank,unemp=ranking('unemployment_pct'),urow=unemp.rows.find(x=>x.iso3===iso),values=unemp.rows.filter(x=>x.value!=null).map(x=>x.value).sort((a,b)=>a-b),median=values[Math.floor(values.length/2)],facts=[];if(base&&latestGdp)facts.push(`${c.name}'s nominal GDP is ${(latestGdp.value/base.value).toFixed(1)}× its 2000 current-dollar level.`);if(nowRank&&oldRank)facts.push(`${c.name} moved from #${oldRank} to #${nowRank} within the Atlas cohort since 2000.`);if(peak&&latestGdp&&peak.year!==latestGdp.year)facts.push(`Nominal GDP remains below its ${peak.year} current-dollar peak.`);if(urow?.value!=null)facts.push(`${c.name}'s ${unemp.ranking_year} unemployment rate is ${urow.value<median?'below':'above'} the cohort median.`);return facts.slice(0,4);}
function country(){const c=countryMeta(state.country),gdp=latest('gdp_current_usd',c.iso3),gdpRank=ranking('gdp_current_usd').rows.find(x=>x.iso3===c.iso3),total=ranking('gdp_current_usd').rows.reduce((s,x)=>s+(x.value||0),0),growth=latest('gdp_growth_pct',c.iso3),pop=latest('population',c.iso3),facts=dataHighlights(c.iso3),groups=[['OVERVIEW',['gdp_current_usd','gdp_growth_pct']],['LIVING STANDARDS',['gdp_per_capita_current_usd']],['PRICES',['inflation_cpi_pct']],['LABOR',['unemployment_pct']],['FISCAL',['central_government_debt_pct_gdp']],['DEMOGRAPHICS',['population']]];return`<div class="controls"><div class="field"><label for="country-select">Economy</label><select id="country-select">${countryOptions([state.country])}</select></div></div><section class="economy-hero"><div><span class="eyebrow">${escapeHtml(c.region)} · ${c.iso3}</span><h2>${escapeHtml(c.name)}</h2><div class="hero-number">${fmt(gdp?.value,'currency',1)}<small>NOMINAL GDP · ${gdp?.year??'UNAVAILABLE'}</small></div></div><div class="hero-context"><div><span class="micro">COHORT RANK</span><strong>${gdpRank?.rank?`#${gdpRank.rank}`:'—'}</strong></div><div><span class="micro">SHARE OF OUTPUT</span><strong>${gdp?`${(gdp.value/total*100).toFixed(1)}%`:'—'}</strong></div><div><span class="micro">REAL GROWTH</span><strong>${fmt(growth?.value,'percent',1)}</strong></div><div><span class="micro">POPULATION</span><strong>${fmt(pop?.value,'integer',0)}</strong></div></div></section><section><span class="eyebrow">DATA HIGHLIGHTS</span><div class="data-highlights">${facts.map(x=>`<div class="highlight">${escapeHtml(x)}</div>`).join('')}</div></section><nav class="section-nav">${groups.map(([name])=>`<a href="#${name.toLowerCase().replaceAll(' ','-')}">${name}</a>`).join('')}</nav>${groups.map(([name,ids])=>`<section id="${name.toLowerCase().replaceAll(' ','-')}"><h3 class="section-title">${name}</h3><div class="${ids.length>1?'grid-2':'history-grid'}">${ids.map(id=>{const m=metric(id);return`<article class="panel compact-chart"><div class="panel-head"><div><h3>${m.name}</h3><div class="panel-sub">${m.unit} · observed values only</div></div>${badge(recency(latest(id,c.iso3)?.year,state.index.metricMax.get(id)).status,recency(latest(id,c.iso3)?.year,state.index.metricMax.get(id)).lag)}</div><div class="chart" data-chart="lines" data-metric="${id}" data-countries="${c.iso3}"></div>${provenance(m,latest(id,c.iso3))}</article>`}).join('')}</div></section>`).join('')}<h3 class="section-title">RELATIVE POSITION</h3>${relativeTable(c.iso3)}<h3 class="section-title">DATA COVERAGE</h3>${countryCoverage(c.iso3)}`;}
function compare(){const selected=state.compare.filter(countryMeta),m=metric(state.metric),mode=state.compareMode,asset=state.rankings.get(state.metric),r=asset?ranking(state.metric):null;return`<div class="brief"><div><span class="eyebrow">MULTI-ECONOMY ANALYSIS</span><h2>Compare economic scale and trajectory.</h2><p>Switch analytical modes to compare levels, normalized growth paths, cohort rank, or exact-period change without changing the underlying observations.</p></div></div><div class="controls"><div class="field"><label for="compare-countries">Economies · 2–6</label><select id="compare-countries" multiple size="5">${countryOptions(selected)}</select></div>${metricSelect()}${timeRangeControls()}</div><div class="mode-tabs" role="group" aria-label="Comparison mode">${['absolute','indexed','rank','change'].map(x=>`<button data-mode="${x}" class="${mode===x?'active':''}" ${x==='indexed'&&!m.indexing_allowed?'disabled':''}>${x.toUpperCase()}</button>`).join('')}</div><section class="compare-strip">${selected.map((iso,i)=>{const o=latest(state.metric,iso),row=r?.rows.find(x=>x.iso3===iso),reference=latest(state.metric,selected[0]);return`<article class="compare-economy" style="border-top:3px solid ${colors[i]}"><span class="eyebrow">${iso}</span><strong>${fmt(o?.value,m.format,m.preferred_decimals)}</strong><span class="micro">${countryMeta(iso).name} · ${o?.year??'Unavailable'}${row?.rank?` · #${row.rank}`:''}${i&&reference&&o?` · ${Math.round(o.value/reference.value*100)}% of ${selected[0]}`:''}</span></article>`}).join('')}</section><section class="panel"><div class="panel-head"><div><h3>${m.name} · ${modeLabel(mode)}</h3><div class="panel-sub">${mode==='rank'?'Rank within Atlas analytical cohort · 1 is highest':mode==='change'?'Change from selected start year':mode==='indexed'?`${state.baseYear} = 100`:m.unit}</div></div><div class="chart-toolbar"><button class="chart-action" data-copy-chart>Copy link</button></div></div><div class="chart" data-chart="compare-product" data-metric="${state.metric}" data-countries="${selected.join(',')}" data-mode="${mode}"></div>${provenance(m)}</section>`;}
function modeLabel(mode){return({absolute:'Absolute values',indexed:'Indexed trajectory',rank:'Historical rank',change:'Change over period'})[mode];}
function explorer(){return`<div class="brief"><div><span class="eyebrow">DESCRIPTIVE ANALYSIS</span><h2>Explore relationships across economies.</h2><p>Each point is one economy observed in the same selected year. Association does not imply causation.</p></div><div class="ranking-summary"><strong>${state.exploreYear} observations</strong><span>Exact-year matches only</span></div></div><div class="controls"><div class="field"><label for="x-metric">Horizontal axis</label><select id="x-metric">${state.data.metrics.map(m=>`<option value="${m.metric_id}" ${m.metric_id===state.xMetric?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label for="y-metric">Vertical axis</label><select id="y-metric">${state.data.metrics.map(m=>`<option value="${m.metric_id}" ${m.metric_id===state.yMetric?'selected':''}>${m.name}</option>`).join('')}</select></div><div class="field"><label for="bubble-metric">Bubble size</label><select id="bubble-metric"><option value="none">None</option>${['gdp_current_usd','population'].map(id=>`<option value="${id}" ${id===state.bubbleMetric?'selected':''}>${metric(id).name}</option>`).join('')}</select></div><div class="field"><label for="explore-year">Year</label><select id="explore-year">${years().slice().reverse().map(y=>`<option ${y===state.exploreYear?'selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="country-highlight">Highlight</label><select id="country-highlight">${countryOptions([state.country])}</select></div></div><section class="panel"><div class="panel-head"><div><h3>${metric(state.xMetric).name} × ${metric(state.yMetric).name}</h3><div class="panel-sub">Common-year descriptive scatter · click a point to open its economy profile</div></div><span class="coverage-chip" id="scatter-coverage">Calculating coverage</span></div><div class="chart scatter" data-chart="scatter"></div>${provenance(metric(state.xMetric))}${provenance(metric(state.yMetric))}</section><h3 class="section-title">OBSERVATION TABLE</h3>${scatterTable()}`;}
function scatterRows(){return state.data.countries.map(c=>({c,x:at(state.xMetric,c.iso3,state.exploreYear),y:at(state.yMetric,c.iso3,state.exploreYear),size:state.bubbleMetric==='none'?null:at(state.bubbleMetric,c.iso3,state.exploreYear)})).filter(r=>r.x&&r.y);}
function scatterTable(){const rows=scatterRows();return`<div class="table-wrap"><table><thead><tr><th>Economy</th><th class="num">${metric(state.xMetric).name}</th><th class="num">${metric(state.yMetric).name}</th><th>Year</th></tr></thead><tbody>${rows.sort((a,b)=>b.x.value-a.x.value).map(r=>`<tr><th class="country-cell">${r.c.name}<small>${r.c.iso3}</small></th><td class="num">${fmt(r.x.value,metric(state.xMetric).format,metric(state.xMetric).preferred_decimals)}</td><td class="num">${fmt(r.y.value,metric(state.yMetric).format,metric(state.yMetric).preferred_decimals)}</td><td>${state.exploreYear}</td></tr>`).join('')}</tbody></table></div>`;}
function methodology(){const sections=[['Universe',`Atlas selects only explicitly included analytical entities and ranks common-year nominal GDP. The current World Bank provider does not contain Taiwan; common-year consistency therefore does not imply complete global candidate coverage.`],['Metrics',state.data.metrics.map(m=>`<p><b>${m.name}</b> · <code>${m.code}</code><br>${m.description}<br><span class="micro">${m.unit} · ${m.caveats}</span></p>`).join('')],['Ranking methodology','Every ranking declares one year. Only a non-null observation in that exact year receives a rank. Ties resolve by ISO3; older observations appear only as labelled context.'],['Observation recency','Current year means lag 0 from the metric maximum, prior year means lag 1, historical means lag 2+, and unavailable means no observation. Retrieval date never substitutes for observation year.'],['Missing data','Atlas never silently interpolates, carries values forward, or displays zero for unavailable data.'],['Sources',`World Bank — World Development Indicators · retrieved ${shortDate(state.data.meta.generated_at)}. Indicator-level definitions and release lineage are available beside every analytical view.`],['Releases',`Atlas Data Release ${shortDate(state.data.meta.generated_at)} · technical ID ${state.data.meta.release_id} · pipeline ${state.data.meta.pipeline_run_id}.`],['Known limitations','The cohort is fixed to the current approved analytical-entity registry. Central-government debt has substantially lower same-year coverage than other metrics. Current-dollar levels reflect both real activity and price/exchange-rate movements.']];return`<div class="brief"><div><span class="eyebrow">REPRODUCIBLE BY DESIGN</span><h2>Methodology</h2><p>Plain-language rules first; technical definitions remain available for scrutiny.</p></div></div>${trustStrip()}<div class="method">${sections.map(([title,body],i)=>`<details ${i<2?'open':''}><summary>${title}</summary><div>${body}</div></details>`).join('')}</div>`;}
function bindProduct(){$$('[data-country-link]').forEach(x=>x.addEventListener('click',()=>go('country',{country:x.dataset.countryLink})));$$('[data-mode]').forEach(x=>x.addEventListener('click',()=>{state.compareMode=x.dataset.mode;syncUrl();render()}));$('#x-metric')?.addEventListener('change',e=>{state.xMetric=e.target.value;syncUrl();render()});$('#y-metric')?.addEventListener('change',e=>{state.yMetric=e.target.value;syncUrl();render()});$('#bubble-metric')?.addEventListener('change',e=>{state.bubbleMetric=e.target.value;syncUrl();render()});$('#explore-year')?.addEventListener('change',e=>{state.exploreYear=+e.target.value;syncUrl();render()});$('#country-highlight')?.addEventListener('change',e=>{state.country=e.target.value;syncUrl();render()});$$('[data-copy-chart]').forEach(x=>x.addEventListener('click',copyView));}
function drawProductCharts(){if($('[data-chart="treemap"]'))treemap();if($('[data-chart="distribution"]'))distributionChart();$$('[data-chart="compare-product"]').forEach(drawCompareProduct);$$('[data-chart="scatter"]').forEach(drawScatter);enableChartTooltips();}
function drawCompareProduct(el){
  const mode=el.dataset.mode,ids=el.dataset.countries.split(','),id=el.dataset.metric;
  if(mode==='rank'){
    const asset=state.rankings.get(id),sets=ids.map(iso=>({iso,rows:asset.available_ranking_years.filter(y=>y>=state.startYear&&y<=state.endYear).sort((a,b)=>a-b).map(year=>{const row=asset.rankings[String(year)].rows.find(x=>x.iso3===iso);return row?.rank?{year,value:row.rank}:null}).filter(Boolean)}));
    renderLine(el,sets,'Rank within Atlas cohort · 1 is highest',performance.now(),id,true);return;
  }
  const sets=ids.map(iso=>{const rows=series(id,iso).filter(o=>o.value!=null&&o.year>=state.startYear&&o.year<=state.endYear),base=mode==='indexed'?at(id,iso,state.baseYear)?.value:rows[0]?.value;return{iso,rows:rows.map(o=>{let value=o.value;if(mode==='indexed')value=base?o.value/base*100:null;if(mode==='change')value=base?(o.value/base-1)*100:null;return{...o,value}}).filter(o=>o.value!=null)}});
  renderLine(el,sets,mode==='indexed'?'Index = 100':mode==='change'?'Change from start (%)':metric(id).unit,performance.now(),id);
}
function drawScatter(el){const rows=scatterRows();if(!rows.length){el.innerHTML='<div class="empty">No common-year observations for this selection.</div>';return}const W=900,H=500,p={l:76,r:30,t:24,b:54},xs=rows.map(r=>r.x.value),ys=rows.map(r=>r.y.value),sizes=rows.map(r=>r.size?.value||1),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),maxS=Math.max(...sizes),x=v=>p.l+(v-minX)/(maxX-minX||1)*(W-p.l-p.r),y=v=>H-p.b-(v-minY)/(maxY-minY||1)*(H-p.t-p.b),radius=v=>state.bubbleMetric==='none'?6:4+Math.sqrt(v/maxS)*17;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scatterplot of ${escapeHtml(metric(state.xMetric).name)} and ${escapeHtml(metric(state.yMetric).name)} in ${state.exploreYear}"><title>Common-year economic scatterplot</title><desc>${rows.length} economies with both observations. Association does not imply causation.</desc>`;for(let i=0;i<5;i++){const gx=p.l+(W-p.l-p.r)*i/4,gy=p.t+(H-p.t-p.b)*i/4;svg+=`<line x1="${gx}" y1="${p.t}" x2="${gx}" y2="${H-p.b}" class="grid-line"/><line x1="${p.l}" y1="${gy}" x2="${W-p.r}" y2="${gy}" class="grid-line"/>`}svg+=`<text x="${W/2}" y="${H-12}" text-anchor="middle" class="axis-label">${escapeHtml(metric(state.xMetric).name.toUpperCase())}</text><text x="16" y="${H/2}" transform="rotate(-90 16 ${H/2})" text-anchor="middle" class="axis-label">${escapeHtml(metric(state.yMetric).name.toUpperCase())}</text>${rows.map(r=>`<circle tabindex="0" class="scatter-dot ${r.c.iso3===state.country?'selected':''}" cx="${x(r.x.value)}" cy="${y(r.y.value)}" r="${radius(r.size?.value||1)}" fill="${r.c.iso3===state.country?'var(--chart-3)':'var(--chart-1)'}" data-country-link="${r.c.iso3}" data-tip="${escapeHtml(`${r.c.name}|${metric(state.xMetric).name}: ${fmt(r.x.value,metric(state.xMetric).format)}|${metric(state.yMetric).name}: ${fmt(r.y.value,metric(state.yMetric).format)}|${state.exploreYear}`)}"><title>${r.c.name}: ${fmt(r.x.value,metric(state.xMetric).format)}, ${fmt(r.y.value,metric(state.yMetric).format)}</title></circle>`).join('')}</svg>`;el.innerHTML=svg;$('#scatter-coverage').textContent=`${rows.length}/50 economies · ${state.exploreYear}`;$$('[data-country-link]',el).forEach(x=>x.addEventListener('click',()=>go('country',{country:x.dataset.countryLink})));}
function enableChartTooltips(){const tip=$('#chart-tooltip');$$('[data-tip]').forEach(mark=>{const show=event=>{tip.innerHTML=mark.dataset.tip.split('|').map((x,i)=>i?`<span>${escapeHtml(x)}</span>`:`<strong>${escapeHtml(x)}</strong>`).join('<br>');tip.hidden=false;const box=mark.getBoundingClientRect();tip.style.left=`${Math.min(innerWidth-240,box.left+12)}px`;tip.style.top=`${Math.max(8,box.top-80)}px`};mark.addEventListener('mouseenter',show);mark.addEventListener('focus',show);mark.addEventListener('mouseleave',()=>tip.hidden=true);mark.addEventListener('blur',()=>tip.hidden=true)});}

init();
